### ISSUE TITLE
Changing orientation on tablet screws up voltage bars

### ISSUE THREAD

**Issue by NikSudan** [gamejolt/next-issue-tracker#112]
![30e089756b274374feed765354c00d107c6832030137023ee8pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/6004491/6340243/473d874c-bbb5-11e4-9b42-847be4f24abc.jpg)

This could just be an iPad issue.

Happens on iPad mini, Safari 8. 768 x 927 browser size.

**Comment by hworld** [comment]
Is this still happening?

**Comment by hworld** [comment]
@NikSudan ping

**Comment by hworld** [comment]
@NikSudan still happening yo man bro dude huh?

**Comment by NikSudan** [comment]
SORRY

**Comment by NikSudan** [comment]
Can't replicate it.
