### ISSUE TITLE
My Activity Feeds are all gone.

### ISSUE THREAD

**Issue by Dragonify** [gamejolt/next-issue-tracker#1199]
Today I woke up and checked my activity feed like usual. But it's empty now. I don't see any activity feed at all. My followed games are all still there, their devlogs are still visible, it just never appear in my activity feed.

**Comment by nilllzz** [comment]
The issue should be solved, can you check if it is for you, @Dragonify ?

**Comment by Dragonify** [comment]
It’s fixed now. Thanks.

**Comment by nilllzz** [comment]
Thanks for confirming, closing this.
