### ISSUE TITLE
Naming or renaming a game-playlist is not possible on Firefox

### ISSUE THREAD

**Issue by MausGames** [gamejolt/next-issue-tracker#120]
The input-box stays inactive when clicking on it, no text-cursor appears, though it's possible to select the label above and hit the tab-button to get into the box - clicking removes the cursor again.

**Firefox 35.0.1 - Windows 7 SP1 x64**
works normal on **IE11** and **Opera beta 28.0**

**Comment by hworld** [comment]
Seems to be a bug with any form in a modal. It happens in the "change token" form as well. What's weird is that you can right click on the input box and it'll focus. I think it has something to do with a click handler being attached and capturing it in FF for some reason.

**Comment by MausGames** [comment]
Disabling the mousedown-event of the modal box itself fixes the problem.
![modal](https://cloud.githubusercontent.com/assets/6109189/6546105/752e3a52-c5a6-11e4-92da-c69c81223100.png)

**Comment by hworld** [comment]
Fixed.
