### ISSUE TITLE
Critical error upon adding media SketchFab and YouTube

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1210]
I'm just speaking on behalf of someone who put this onto the forums.
Click the screenshot to get to the specific thread!

[![image](https://user-images.githubusercontent.com/11202073/48206318-6e39f580-e36e-11e8-85c3-966d1bb4653f.png)](https://gamejolt.com/f/fix-stuff/344102#forum-post-446372)

**Comment by nilllzz** [comment]
I was unable to reproduce this.
This is the corresponding forum topic:
https://gamejolt.com/f/fix-stuff/344102

**Comment by hworld** [comment]
Can't repro
