### ISSUE TITLE
Pagination wording on forum channels and topics looks weird

### ISSUE THREAD

**Issue by YLivay** [gamejolt/next-issue-tracker#1211]
Says "Page X of Y topics." in channels and " Page X of Y replies." in topics.

Should probably just be "Page X / Y" or even better, remove that pagination text and use an actual pagination component instead.

**Comment by nilllzz** [comment]
This also happens in game listings "Page X of Y games."
Aside from that, isn't this a suggestion and therefore belongs on the gj-improve forum?

Pagination is kinda mentioned here: https://github.com/gamejolt/issue-tracker/issues/958
