### ISSUE TITLE
Forums and Search options in sidebar are not linked correctly

### ISSUE THREAD

**Issue by nilllzz** [gamejolt/next-issue-tracker#1214]
When visiting the Search page on mobile and looking at the sidebar navigation, it highlights both Search and Forums.
![image](https://user-images.githubusercontent.com/2119926/48269078-f1bf1980-e436-11e8-96d3-81cd9afda519.png)
Similarly, when visiting Forums, it doesn't highlight any option.
![image](https://user-images.githubusercontent.com/2119926/48269100-026f8f80-e437-11e8-8269-2d8fe62a126a.png)

**Comment by hworld** [comment]
Fixed
