### ISSUE TITLE
Game Follow Button showing in incorrect position

### ISSUE THREAD

**Issue by nilllzz** [gamejolt/next-issue-tracker#1217]
When resizing a game page in a certain way, the Follow button shows up in an incorrect place.
![image](https://user-images.githubusercontent.com/2119926/48520488-18cf7e00-e871-11e8-9cd3-77c438e227c0.png)

**Comment by hworld** [comment]
Fixed this in https://github.com/gamejolt/gamejolt/commit/6e14d67a9296971564bb3306f059e38351b2892c
