### ISSUE TITLE
Tags link to the old site

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#122]
I clicked a tag on one of the game pages (in this case that was "#fantasy" on my page for Dyrt) and I was dropped back on the original GameJolt where the results did show normally, but I suppose that getting back onto the old page was not supposed to happen.

**Comment by hworld** [comment]
Yeah, "search by tag" isn't done yet in Next, so there's no place to direct to yet for tags.

**Comment by hworld** [comment]
I added in tag pages/sections so I was able to link them correctly now.
