### ISSUE TITLE
problem with Gamejolt Client

### ISSUE THREAD

**Issue by Sebby07** [gamejolt/next-issue-tracker#1222]
**How are you using Game Jolt?**
With the browser version, since client isn't working properly.

**Please describe the issue you are having**
So, about a month or 2 ago, Gamejolt Client started doing this thing, where whenever i open it, it says it's trying to 'migrate games', but it can't because 'i have games open'. The only thing i had open, was the client itself. Now, i've tried again, and instead, it's making me log in, but when i do, the afore-mentioned 'migration' screen pops up for a second, then it just goes back to the log in page. Please help
EDIT; Forgot to mention that 2 months ago, i tried reinstalling the client, didn't work. But i just tried again earlier, and it did work, so the problem's fixed. But still, the glitch might still be lingering, so please check for that.

**Comment by hworld** [comment]
Thanks for letting us know that you got it working. We'll make sure that people are installing the new Client to get the fix.
