### ISSUE TITLE
Opera cuts an essential part out of the page

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#123]
![image](https://cloud.githubusercontent.com/assets/11202073/6383873/a24fbf6e-bd55-11e4-9816-ebe1c71357a5.png)

I don't know how this is in other browsers as I only tried this in Opera (for Mac) yet. I do have Firefox, Safari and Chrome installed as well, so I may try this out there later as well.
Opera has no status bar at the bottom of the screen (at least not by default), in stead of that cuts a part out of the website, however as my own avatar and the "logout" link are in the part that is cut out, this is a little bit annoying since you can't scroll down. 
On the bright side Opera did take into account that when my mouse pointer is there to click my avatar to see my own profile or to logout, the "cutout" appears on the bottom right corner, making the issue not that severe. Only a bit annoying.

**Comment by hworld** [comment]
Yeah, that's a webkit thing, so chrome, opera, and maybe safari. It is pretty annoying and I've noticed it to. They solve it by that switching to other side of the screen that they do. The only solution to this is to move that user box somewhere else, but it works well there right now. I'm going to close this as wontfix, but if enough people complain about it, I may have to redesign it. =\
