### ISSUE TITLE
Devlog Game Can't Transition To Early Access

### ISSUE THREAD

**Issue by 78Alpha** [gamejolt/next-issue-tracker#1232]
**How are you using Game Jolt?**
As a developer and marketplace user.

**Please describe the issue you are having**
The game devlog page states that I need to have a publicly active package to switch to early access but the package can't be made public until the game is switched to early access.

This means it is an infinite loop, such that no devlog only game can be put into early access without creating a separate page.

**Comment by YLivay** [comment]
Which game are we talking about? can you link the game page? Also, did you try refreshing?

**Comment by 78Alpha** [comment]
https://photos.app.goo.gl/uezPWh6RbMphnt5u9

Pictures of the problem pages 

https://gamejolt.com/games/_Necro_/384336

And the actual game page.

**Comment by noahmaue** [comment]
I have the same issue. Can't figure it out...

**Comment by Tricky1975** [comment]
You can "fix" this issue, by simply renewing the page AFTER you uploaded and published the first valid package. I was suffering the same issue when uploading my newest project. 

# IMPORTANT NOTE!

Only renew once you've SAVED all settings you recently changed, or they may get lost! 

Of course, this being set right, without having to renew would be by far more elegant!
