### ISSUE TITLE
I cannot unfollow banned users

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1233]
![image](https://user-images.githubusercontent.com/11202073/50375479-404b0080-05fe-11e9-9f88-76f014e1a239.png)

The followed account belongs to a spammer, and see what happens when I try to unfollow it (I clicked multiple times, and thus the multiple "Oh No!" messages). Of course as a moderator I can simple unban the account and unfollow it and ban it again, but that solution is not elegant and since normal users cannot do this, I think this is an issue.

**Comment by YLivay** [comment]
We're planning on auto purging banned users from existance after 1-2 weeks since their ban took effect. This issue will be resolved then. Leaving the issue open till that plan carries out.

**Comment by Tricky1975** [comment]
Sounds cool to me... In the past however I've seen people being temporarily banned at their own request for, for example school exams... Will this no longer be possible? (of course I guess GJ was a smaller community back then).
