### ISSUE TITLE
Game pages beyond page 248 => error 404

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1234]
**How are you using Game Jolt?**
- Firefox (mac)
- Chrome (windows) (user who alerted me on this one).

**Please describe the issue you are having**
As soon as you go beyond page 248 when browsing game pages (no matter which channel) a 404 error pops up. Page 248 works... Page 249 and above do not.

**Comment by Tricky1975** [comment]
(Oh, and I managed to get a very nice issue number, lol)

**Comment by YLivay** [comment]
We know about this, i'm not sure what we should do about this tho. It's a restriction of the way we do pagination. We could either prevent going over page ~200 or so, or redo our pagination. @hworld what do you think we should do for this?
