### ISSUE TITLE
Very big font

### ISSUE THREAD

**Issue by JNyknn** [gamejolt/next-issue-tracker#124]
Not sure has anyone already reported this, but sometimes when I open a game page, it looks like this:
![Bug](https://dl.dropboxusercontent.com/u/98638115/error_gj.png)

**Comment by acidpoison** [comment]
Hasn't happened to me yet.

**Comment by hworld** [comment]
Holy crap, what? Can anyone else reproduce that? I've never seen it in all my testing.

**Comment by Feargeorge** [comment]
I have went on the same page and didn't get any big font, it was all normal.

http://prntscr.com/6a55hg

**Comment by MausGames** [comment]
Can confirm on **Firefox 36.0 Windows 7 SP1 x64**

Apparently it is caused by the CSS property:

    .package-title {
         font-size: 300px;
    }

**Comment by hworld** [comment]
Hahaha, yikes! That's a bug for sure. Not even sure how it crept in to the stylesheet. Anyway, fixed.
