### ISSUE TITLE
I can't upload the required thumbnail.

### ISSUE THREAD

**Issue by noahmaue** [gamejolt/next-issue-tracker#1240]
**How are you using Game Jolt?**
As a developer/hobbyist.

**Please describe the issue you are having**
When making a new game, I can upload a package, and all of that other stuff. But when I try to upload the required thumbnail, I get this: [![Screenshot from Gyazo](https://gyazo.com/ef25edfc35f79be6ec4fd45ac5f4710e/raw)](https://gyazo.com/ef25edfc35f79be6ec4fd45ac5f4710e)

Can someone please help me figure out why this keeps happening? I've been trying for about a week now, and still nothing. And I've tried the CLIENT as well as my BROWSER. Here's the thumbnail, if that helps.

![fabulous](https://user-images.githubusercontent.com/32719997/51285085-c703bb00-19bb-11e9-89dd-296490f95065.jpg)

Thanks in advance.

**Comment by YLivay** [comment]
Does this still happen for you? It should've been fixed a few weeks ago

**Comment by YLivay** [comment]
Closed for inactivity
