### ISSUE TITLE
Client won't run

### ISSUE THREAD

**Issue by SQUAREGUY88** [gamejolt/next-issue-tracker#1242]
It says that client is running but it is not. I can't fix it.

**Comment by YLivay** [comment]
What tells you that the client is already running? Can you paste a screenshot?

**Comment by Yuki0Nova** [comment]
![image](https://user-images.githubusercontent.com/50278148/57185513-ce7f9f00-6e9a-11e9-8575-5c2a61765f45.png)

**Comment by Yuki0Nova** [comment]
That's what it always says.

**Comment by Yuki0Nova** [comment]
The first time I downloaded it worked very well, but then the next day it said that.

**Comment by Sillybadwolf** [comment]
I am having the same problem, too. :(

**Comment by Yuki0Nova** [comment]
Yeah but I waited about two weeks and it worked so maybe they fixed it.

**Comment by YLivay** [comment]
You've been re-running the installer. The client should create a desktop icon for it. you should be using that instead of the installer after its installed :)

**Comment by Yuki0Nova** [comment]
Thanks for the help.
