### ISSUE TITLE
the devlog for my new game only loads the description and nothing else

### ISSUE THREAD

**Issue by quackquackk** [gamejolt/next-issue-tracker#1243]
**How are you using Game Jolt?**

I'm starting to make a new game.
**Please describe the issue you are having**

So, in the web version,  The whole thing does not ever load! the devlog is here: https://quackquack23.gamejolt.io/cameron-and-freinds/
If you can help, I would appreciate that.

**Comment by YLivay** [comment]
Hey, the custom site is not like the game page on game jolt - not everything is available there. We offer a few widgets like an image galltery, widget to embed your package and a widget to embed your game description. You must've only used the description widget in your site.

https://help.gamejolt.com/widgets-game-site
