### ISSUE TITLE
Thumbnail and devlog gifs seem to be failing sometimes

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/next-issue-tracker#1248]
Have received emails from multiple users stating that thumbnail and devlog gifs don't seem to be loading all the time. Seems to work sometimes but not always.

_Detailed excerpt from one report:_

> "When I check the dev console in Chrome I see that the website tries to load a jpg image (a preview thumbnail I guess?) and that gives a 500 internal server error. Also iff I browse to such URL manually it shows "Internal Server Error".
> 
> Here's an example post:
> https://gamejolt.com/games/source-of-madness/362485/devlog/creeps-in-the-making-with-machine-learning-we-ll-get-more-interest-ur6jsge5
> 
> The thumbnail link that fails to load is
> https://m.gjcdn.net/fireside-post-image/900/1785838-sdp4zq4f-v3.jpg
> 
> If I click into the page from another page I see the gif. But if I press F5 to reload, the gif doesn't show up."

Tested the above myself and the gif did seem to load for me. I do receive an internal server error on the thumbnail link though.

**Comment by nilllzz** [comment]
Should be fixed
