### ISSUE TITLE
User recieving a "Connection error" when game upload reaches 100%

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/next-issue-tracker#1249]
A user keeps receiving a connection error when their game upload reaches 100%. Maybe the processing stage is failing for some reason?

This is the game they are trying to update: https://gamejolt.com/games/generalpractitioner/367922

Quote from email:
"Recently I’m having a lot of issues uploading a release of the game. Whenever I patch the game I upload about 1.6 GB of data. Even though my internet connection is very fast the upload on your website takes a while and when I reach 100% I receive a “Connection error” 9 out of 10 times."

**Comment by YLivay** [comment]
I'm looking into this. I think the connection is being timed out on the user's end. Probably some default browser setting changed and we aren't allowed to have as much time during the user session to do the initial processing of the files. Hopefully this will be resolved this week!

**Comment by YLivay** [comment]
Just updating, I have a fix ready but due to the issues we were having lately I had to delay pushing this.

**Comment by YLivay** [comment]
This should be fixed now. We also pushed some better error reporting for common cases where the build was left eternally in "processing" phase.
