### ISSUE TITLE
Game Jolt Client not opening

### ISSUE THREAD

**Issue by Dragonify** [gamejolt/next-issue-tracker#1251]
I have set my Game Jolt client to automatically open every time I boot up my PC. And normally I will close it and make it only running on background. However, the app often doesn't open when I open the window back, and I have to forcefully end its task with task manager (the app is suspended as the task manager says). And sometimes when I reopen it again it just shows a white screen. What is happening? Is it my PC problem or the Client problem? This has been happening for a while now and I thought the latest version has fixed it, apparently it's not.

**Comment by YLivay** [comment]
hmmm... it's the second report I saw about this. I can't reliably reproduce it on my end. We didn't do any changes that might affect this except updating the nwjs version. Maybe that introduced a bug with rendering the client? I can try pushing another version with a newer version (by now if such a bug existed I hope it got patched up!)

**Comment by Dragonify** [comment]
I really hope you can fix it, 'cuz it just cause a new horrible problem:
I restart my computer the other day, and the shortcut icon of the Client disappeared, and I checked out what happened, it seemed that it has deleted itself from the computer, and the shortcut can't be located anymore. I can't do anything anymore other than removing it from my desktop.
I did re-download it later on, but the same thing happened: the app freezes, it shows a white screen, and it deleted itself.
I'm not sure if this is my computer problem or not, but I hope a solution can be found.

**Comment by YLivay** [comment]
The client doesn't delete any of its own files besides the client.log. At this point it sounds like a hyperactive anti virus actually. Which one do you run? Can you check quarantine to see if some file that was originally in the client directory got removed?

**Comment by YLivay** [comment]
Closed for inactivity
