### ISSUE TITLE
Trying to open a Markdown link with no HTTPS:// results in a 404 error page.

### ISSUE THREAD

**Issue by igorvasiak** [gamejolt/next-issue-tracker#1253]
I've made a post [here](https://gamejolt.com/games/dontdie/389519/devlog/skills-skills-skills-skills-and-more-skills-vcuvm9xz). On this post I have two links, both redirecting to the same page. Both are bit.ly links. The links should take you to bit.ly/dontdie-trello, but Game Jolt tries to add, weirdly, this to the link:  

https://gamejolt.com/games/dontdie/

So now it looks like:

https://gamejolt.com/games/dontdie/bit.ly/dontdie-trello

I wrote the link like this:

Don't Die's Trello board (bit.ly/dontdie-trello)

Instead of:

Don't Die's Trello board (https://bit.ly/dontdie-trello)

Which fixes the issue.

Is the site supposed to do that to the short versions of the links (rhetoric question)? If so, just ignore my ignorance! 😄 
I hope I'm not being inconvenient. Thanks for your consideration.

**Comment by YLivay** [comment]
That is weird, seems like it thought that link was a relative url for some reason. It shouldn't be doing that, thanks for reporting!

**Comment by YLivay** [comment]
@nilllzz this will be resolved with contentidor, right?

**Comment by Tricky1975** [comment]
Leaving out the protocol is a mortal sin in HTML and and transcompiling markup languages for HTML such as BBCode and MarkdDown. The system will then always assume the same folder for a new html file. This is just the way browsers are coded as that's the standard. When leaving the server the page is on, always include the protocol.

~~~markdown
[my link](www.tbbs.nl)
~~~
Will translate to <a href='www.tbbs.nl'>my link</a> which won't work.

Correct link!
~~~markdown
[my link](http://www.tbbs.nl)
~~~
Now [my link](http://www.tbbs.nl) does work!

I wonder why https://gamejolt.com/games/dontdie/ is the link as it should given the link be https://gamejolt.com/games/bit.ly/dontdie/ but perhaps an autofilter within Game Jolt filters that out later, but the link not working when the protocol is not mentioned in the URL is how links should work by convention.

**Comment by YLivay** [comment]
eyy this is fixed with new content editor!
