### ISSUE TITLE
Scheduled blogs do not appear when set

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1255]
**How are you using Game Jolt?**
Firefox for Windows.

**Please describe the issue you are having**
I've written multiple blogs on various "nice-to-know" topics, the first one to appear was about Blaise Pascal ([In case you are interested](https://gamejolt.com/@Tricky/post/pascal-the-inventor-of-the-computer-or-not-fve64sjw)), and that's also the one making me discover this issue. I scheduled to appear Sunday 12;00am(in my own local time zone, which is GMT+1). This because I've many blogs already and I don't want to make them appear all at once, but with some intervals so i can keep people interested. However the blog never appeared, and every time I checked the clock for making it appear magically set up more and more time before it would appear. I tried to "force things" by scheduling only 4 minutes ahead. GJ correctly noted that. When I checked 15 minutes later, it was suddenly 6 hours or even more away and it kept going up rather rapidly, but in the end I had to manually remove the schedule in order to make it appear, and was that really how scheduling was supposed to be working?

**Comment by YLivay** [comment]
Is this a one time occurence of does it keep happening? It may be related to the issues we were having around that time. This is not how this should work - the posts should optimially go out when you schedule them to, and if we don't have any backlog of tasks at the time - within less than a minute of the scheduled time. We'll check it out.

**Comment by Tricky1975** [comment]
I cannot be sure... My blog about Blaise Pascal had its schedule times modified a few times and perhaps that is what caused that to happen, as an other blog did appear when it should but there the time was never changed.

**Comment by YLivay** [comment]
I can't recreate this, sounds like it couldve been a really weird rare one off issue. I'm closing this issue for now, if this happens again, lmk and i'll reopen it.
