### ISSUE TITLE
Dupe growls

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1256]
**How are you using Game Jolt?**
Firefox in Windows

**Please describe the issue you are having**
When I have multiple Windows/Tabs (mod pages not counted) open on Game Jolt and somebody sends me a chat I get the growl as much times as there are tabs open. So if I have 5 tabs open and CROS would send "Hello Jeroen" to me, I would get 5 growls in once saying "CROS says: Hello Jeroen". No matter how many Windows/Tabs I have open, I think 1 growl suffices.

**Comment by YLivay** [comment]
We know of this issue, atm I don't know what we'll do about it. @nilllzz got any ideas on deduping? that can't be on grid's end right?
