### ISSUE TITLE
Page numbers on games listings don't actually load in the next page of games

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/next-issue-tracker#1259]
Found an interesting little bug. On any game listings page, New, Hot, Best and Featured; The page number controls don't change the games listed. The page number in the url changes, but the games listed don't actually change. Ctrl + F5 causes it to load normally.

Using latest Firefox:
- Go to: https://gamejolt.com/games/new
- Scroll down.
- Click a page number or next.
- The page will "load" but the games list will not change.
- Ctrl + F5 while on a page with a number, e.g. "/new?page=2" will cause the games to load in properly.

**Comment by YLivay** [comment]
Fixed!
