### ISSUE TITLE
Missing spaces between some elements across the site

### ISSUE THREAD

**Issue by TheCrafters001** [gamejolt/next-issue-tracker#1260]
**How are you using Game Jolt?**
I just use it like a normal user

**Please describe the issue you are having**
THIS
![Capture2](https://user-images.githubusercontent.com/46639269/55270177-6376f300-5272-11e9-9dc3-bc9845720beb.PNG)
![Capture](https://user-images.githubusercontent.com/46639269/55270178-65d94d00-5272-11e9-8228-dd1ff3420c76.PNG)
Bugs me.

**Comment by YLivay** [comment]
This is a spacing issue we're working on fixing atm.
Thanks for reporting, im keeping it open for reference till we push the fix

**Comment by TheCrafters001** [comment]
> This is a spacing issue we're working on fixing atm.
> Thanks for reporting, im keeping it open for reference till we push the fix

Alright.

**Comment by YLivay** [comment]
Fixed
