### ISSUE TITLE
I can't read the schedule settings

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1261]
**How are you using Game Jolt?**
Firefox in Windows

**Please describe the issue you are having**
Better perhaps to show you:
![image](https://user-images.githubusercontent.com/11202073/55282490-f5e7c700-5344-11e9-860d-0a8c8a58f7ab.png)
Can you see which month I'm setting? I don't have a clue....

**Comment by TheCrafters001** [comment]
June. :) I can see it, kinda. But I see June 2019.

**Comment by Tricky1975** [comment]
Geez, you've good eyes....

**Comment by qwertychouskie** [comment]
It all depends on screen angle.  Tilting back the screen increases contrast, I use this every so often to see low-contrast stuff.

**Comment by Tricky1975** [comment]
Yeah, I noticed, yet, such things should not be needed

**Comment by TheCrafters001** [comment]
> It all depends on screen angle. Tilting back the screen increases contrast, I use this every so often to see low-contrast stuff.

I can see it just fine without a angle.

**Comment by Tricky1975** [comment]
Some monitors differ in color mode. It can only mean your monitor does not show all colors the way they should, or that you have eyes with a better color distinguish features than they should have. Quite a nice gift, but that's not what we should base this on 😝

**Comment by Tricky1975** [comment]
I see this has been fixed, thank you ;)
