### ISSUE TITLE
Maturity rating cannot be set anymore for some odd reason

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1262]
I'm now merely speaking on behalf of people who [reported this on the forums](https://gamejolt.com/f/gamejolt-has-software-gore-too/344879#forum-post-450795). I think this issue really needs fixing, especially when people are uploading porn game or other games with mature content.

**Comment by Tricky1975** [comment]
![image](https://user-images.githubusercontent.com/11202073/55582343-88121580-571f-11e9-93cd-dc4be22c82d0.png)

Button disabled for "All Ages" and that block sign is my mouse pointer confirming at least that I cannot set the game to "All Ages" anymore.

**Comment by Tricky1975** [comment]
Supplement:
- All ages -> Can't save
- Teen Content -> Saved as "All Ages"
- Mature Content -> Saved as "Teen"

Especially for Mature this can be rather serious.

**Comment by nilllzz** [comment]
Fixed.

**Comment by nilllzz** [comment]
https://github.com/gamejolt/gamejolt/commit/f7cb0a9b820af64e0cb4fb68df225cee2334ade3
