### ISSUE TITLE
Data Store:, Not Update, and Not Remove,, values in keys

### ISSUE THREAD

**Issue by esbvaGames** [gamejolt/next-issue-tracker#1263]
**How are you using Game Jolt?**
esbva:
and my game test,,, no Update or Remove Data-Store values

**Please describe the issue you are having**

You can not update or delete the Data stored in the Data-Store, the HttpRequest does not work

You can not see a list of saved data, even if String lines converted from json format !!!

**Comment by YLivay** [comment]
The game api seems to be working just fine, sounds like an issue with implementation of it.
What library are you using?

**Comment by esbvaGames** [comment]
I use, the python library, and the plugins of godot 3.1, and neither works, does not remove, nor update values, the answer is always false in the store-data, in addition you can not see the store-data, stored on the website, even if they are a string of letters!
See if you can make a video, with python, add, modify, and delete what is stored in the store-data.

**Comment by YLivay** [comment]
We don't maintain any officiall game api libraries. The service seems to be working perfectly fine tho, I quadrupled checked. This is not an issue on Game Jolt's end so I'm closing this issue. You can try contacting the library owner, sounds like its either an issue with how you're using it or an issue with the library itself.
