### ISSUE TITLE
[legal issue] Copyright and license violation

### ISSUE THREAD

**Issue by 4144** [gamejolt/next-issue-tracker#1265]
Hello,
I am author of the mana world game client named [manaplus](http://manaplus.org/)

On your site at url https://gamejolt.com/games/manabreak/401330 present renamed manaplus binaries without any copyrights. Also in game archive missing license and authors files.

Links to manaplus sources: https://gitlab.com/manaplus/manaplus/ and https://github.com/manaplus/manaplus

https://gamejolt.com/games/manabreak/401330 is completly stolen game. Man who posted it on this site not have any relation to manaplus or to the mana world.

Please remove this game from your site.

**Comment by 4144** [comment]
Original manaplus sources and binaries for posted download link on site:
http://download.evolonline.org/manaplus/download/1.8.12.8/manaplus-1.8.12.8.tar.xz
http://download.evolonline.org/manaplus/download/1.8.12.8/windows/manaplus-1.8.12.8-win32.exe

**Comment by MAF-Saulc** [comment]
Hello,
He also stolen this game Jelly Breaker  https://gamejolt.com/games/Jellybreaker/262637
Original game called SlugCaster: https://github.com/Supernaught/slugcaster

**Comment by Proto-ai** [comment]
Removed manabreak from site :/

**Comment by 4144** [comment]
thanks

**Comment by Proto-ai** [comment]
may both issues please be closed

**Comment by 4144** [comment]
sorry reopened

**Comment by Proto-ai** [comment]
why?

**Comment by 4144** [comment]
because you not removed it, but only hide

**Comment by Proto-ai** [comment]
gamejolt doesnt have restricted, it only has hidden

**Comment by Proto-ai** [comment]
which means you can visit with link

**Comment by Proto-ai** [comment]
but its removed on gj

**Comment by Simon-Laux** [comment]
I'm not sure if we should give you the benefit of the doubt @Proto-ai

**Comment by Proto-ai** [comment]
![3078df3cef4cdba8e08620073c59424d](https://user-images.githubusercontent.com/22551631/55676389-18746580-589a-11e9-89cc-a468c8557818.png)

**Comment by Proto-ai** [comment]
i only have 3 things on there right now

**Comment by Proto-ai** [comment]
![74f5925e4c23e0d380e0f953f72ec463](https://user-images.githubusercontent.com/22551631/55676391-288c4500-589a-11e9-8900-c2214692ff60.png)

**Comment by Simon-Laux** [comment]
@Proto-ai changing you names and hiding games won't help. YOU have to be fair and respect the licenses of opensource projects when you use them. PERIOD.
Don't play the victim again. Be an adult -> apologize and fix your mistakes.

**Comment by Proto-ai** [comment]
Im number 1. not an adult lmao, number 2. i fixed it and the game is nonexistant

**Comment by Proto-ai** [comment]
its gone

**Comment by Simon-Laux** [comment]
No one prevents you from forking opensource stuff AS LONG as you follow the rules.

**Comment by Proto-ai** [comment]
Tbh manabreak was kind of just made to boost my reputation before vagabond, aka new game im making that i need to get attention on

**Comment by Simon-Laux** [comment]
Do you ever listened to yourself when you speak?

**Comment by MAF-Saulc** [comment]
@Simon-Laux  We already get issue with this kid when he join our Discord and ask us how to copy the game for his "OWN" repo, at this time we prevent him from license breaking.
And then here we are today!

Manabreak is  pointed issue today but other game license should be inspected too like SlugCaster:

**Comment by Proto-ai** [comment]
Slugcaster was made 2 years ago with the love2d open source engine, any game made with that engine CANT have a license, any exe can be uncompiled using their tools. And all games made with it are not licensed at all.

**Comment by Simon-Laux** [comment]
No License Specified means all rights reserved for creator. AKA. You can NOT use it without explicit consent and allowance of the owner.

**Comment by 4144** [comment]
Got mail what this game was removed. I think issue can be closed
