### ISSUE TITLE
Sometimes buttons don't work. 

### ISSUE THREAD

**Issue by TheCrafters001** [gamejolt/next-issue-tracker#1268]
**How are you using Game Jolt?**
Normally

**Please describe the issue you are having**

Sometimes the buttons, after the squishy buttons update, requires multiple clicks to work.

**Comment by YLivay** [comment]
I think i've seen this happen rarely. Not sure if it's a vue issue with binding the event handlers too late or what. It's not something new from the squishy button feature, i've heard this a while back too.

@hworld thoughts?

**Comment by TheCrafters001** [comment]
@YLivay I am still having issues with the buttons.
I know that you asked @hworld to help, but he still hasn't replied.
