### ISSUE TITLE
Link to forum in sub-menu doesn't work at all sometimes

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1270]
**How are you using Game Jolt?**
Site through FireFox (Windows 10)

**Please describe the issue you are having**
![image](https://user-images.githubusercontent.com/11202073/57509413-787c8280-7304-11e9-9afc-f0e634c38efd.png)

Quite often that link doesn't work at all. No I don't get a 404 error or anything. Just nothing happens, like I never clicked that link. Sometimes after renewing the page, it works again.

**Comment by YLivay** [comment]
I think it has something to do with vue binding clicks too late to components or something. It's not specific to this button and theres a few duplicates of these issues logged already (#1268) so i'm going to close this one.
