### ISSUE TITLE
Client won't open

### ISSUE THREAD

**Issue by Sillybadwolf** [gamejolt/next-issue-tracker#1271]
**How are you using Game Jolt?**
To play games. (duh) Windows 10

**Please describe the issue you are having**
I try to launch the Game jolt Client but my computer says, and I quote, "Setup has detected that Game Jolt Client is currently running. Please close all instances of it now, then click OK to continue, or Cancel to exit."
But the thing is, I closed all instances that I can find but it still won't work. I tried deleting the client completely and then reinstalling it but it still says that it's running. I just want to play games but this stupid bug won't let me. (I tried downloading from the webpage but that won't work for me either, different problem, don't worry about it). I have also downloaded the client before and it worked perfectly but then this happened.
PLEASE HELP!

**Comment by YLivay** [comment]
After installing the client, there should be a desktop icon. You don't launch the client by launching the installer again. If the installer is still complaining about the client being open - open the task manager and kill all processes called "Game Jolt Client" if you see any. The installer should be able to close them for you too, so i'm not sure what issue you are experiencing S:

**Comment by YLivay** [comment]
Closed for now, you can reply here if the issue hasn't been resolved and we'll look into it further :)

**Comment by RealWolf0909** [comment]
i have the same problem, but in the task manager i dont find anything called gamejolt, but the laucnher still says its running...
