### ISSUE TITLE
Gamejolt Client download

### ISSUE THREAD

**Issue by ririStabzU** [gamejolt/next-issue-tracker#1272]
Sow when i download Game Jolt client, and yes ive tried reinstalling it before, it keeps giving me 0.29.3 instead of 0.3.0, so I am unable to download any games because it keeps saying that it cant unpack the game. Please help ive been looking everywhere for a solution
Im not really good when it comes to long explanation paragraphs so any questions about the problem i will respond to asap.

**Comment by YLivay** [comment]
0.29.3 is the lastest version. Which games are you trying to download? Did you change which folder it downloads the games to? If so, make sure you have permissions to write to that folder. Also make sure you have enough disk space.

**Comment by YLivay** [comment]
Closed for inactivity
