### ISSUE TITLE
Unable to select a day when trying to schedule a devlog post

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/next-issue-tracker#1274]
Title pretty much sums it up.

When trying to schedule a devlog post, you can scroll months but you're unable to select a day for the post. Not sure if time works either.

**Comment by Tricky1975** [comment]
I could select a day, but I was unable to see WHICH day... From what I can tell, it DOES appear to work

**Comment by YLivay** [comment]
Fixed
