### ISSUE TITLE
Sells acting weird

### ISSUE THREAD

**Issue by Chloe1234567** [gamejolt/next-issue-tracker#1275]
**How are you using Game Jolt?**
To sell my products 

**Please describe the issue you are having**
It doesn't show as if anything is selected and all the buttons are glitched out where no text or anything is shown.

https://www.youtube.com/watch?v=PGDFqiXR9v4&feature=youtu.be

**Comment by YLivay** [comment]
Sounds related to https://github.com/gamejolt/issue-tracker/issues/1274 which has just been fixed. Please try again :)
