### ISSUE TITLE
Can't edit FireSide posts (well sometimes)

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1279]
I do write some blogs on Game Jolt through the FireSide features, and I often schedule those. Last time I made a mistake with the scheduling date and wanted to edit it, but when I hit the edit button, loading whatever is required next, took forever. I tried this with other blogs, and same issues.

This until the moment I got tired of it, copy and pasted the entire content of the blog to a new post, and deleted the old one and magically I can edit my posts again.... I wonder what happened there....

**Comment by YLivay** [comment]
Around that time we were having some server issues. Its probably related but I can't tell for sure. I'm closing this issue but if you encounter this again contact me. I'll probably have to dig through the logs so the sooner you get me after it happens the better :)
