### ISSUE TITLE
Can't scroll when chatroom open

### ISSUE THREAD

**Issue by mikemacdee** [gamejolt/next-issue-tracker#128]
If the chatroom is open, I can't scroll down to view the recent chat history, nor to enter my own messages. I'm stuck looking at this until I close the chatroom:
http://s13.photobucket.com/user/5thman/media/chat_zpsbagjxzgl.png.html

Friends list scrolls just fine.

**Comment by hworld** [comment]
Hmm, on FF? What if you press F11 to go into full screen mode?

**Comment by mikemacdee** [comment]
It gets super laggy AND I can't scroll the chat.

**Comment by hworld** [comment]
Should be fixed, mike. Any way you can confirm?
