### ISSUE TITLE
The archive you uploaded looks corrupted, we can't extract it on our end.

### ISSUE THREAD

**Issue by kosinaz** [gamejolt/next-issue-tracker#1281]
**How are you using Game Jolt?**
As a dev.

**Please describe the issue you are having**

Until yesterday I was able to upload zip files in Game Dashboard > Overview/Setup > Packages > Manage > New Release > Upload Browser Build.
Today I started to receive the following error message every time I tried to upload a zip file.

```
The archive you uploaded looks corrupted, we can't extract it on our end.
Please re-upload with a valid archive.
```

I tried to re-zipping the same package, tried to upload packages that I was able to upload previously, and also tried to upload earlier packages of other projects into those projects, but received the same error message every time.

I also checked the console but found no related logs that would provide more information about this issue. It seems the upload is successful anyways, and the extracting method is the one that is failing.

Thanks for your help in advance.

**Comment by YLivay** [comment]
Hey, can you share the url of the upload build page you are on? It'll help us figure out if theres any specific issue with the archive youre uploading. In the meantime i'll check if something's gone wrong in general :)

**Comment by YLivay** [comment]
Haha, seems like the disk ran out of space! I'll retry the build processing after this is resolved. Stuck builds should go through in a few hours. I'll update here if there's any issue, hopefully you won't need to reupload your build. Sorry about that ;-;

**Comment by kosinaz** [comment]
Don't worry, I just re-uploaded it without any error. 
Now I'm just getting the following warning:
`This package has builds that are still processing. They will be available in the package as soon as they're finished processing.`

**Comment by YLivay** [comment]
Yeah, it'll take a bit longer until builds are processed. theres a bit a backlog because of the held up tasks from before.

**Comment by kosinaz** [comment]
The package is now processed. Thank you very much. Closing the ticket.
