### ISSUE TITLE
Unable to add score to table by ID with Unity API

### ISSUE THREAD

**Issue by ghost** [gamejolt/next-issue-tracker#1283]
I am using the Unity API by infected_bytes: https://gamejolt.com/games/unity-api/15887

I have tried `Scores.Add(score, scoreText, tableID);` with no luck, the scores always go to the main score table.

The way the ID is defined is `private int tableID = 428009; // Set it to 0 for main highscore table.`

I have double checked that the ID matches the one gamejolt gives me:
![image](https://user-images.githubusercontent.com/20288180/59967171-2ea3d080-952f-11e9-9b66-c8a20707f71d.png)

**Comment by nilllzz** [comment]
Can you paste the entire file from which you posted the snippets above? Maybe there's some variable shadowing going on.

**Comment by nilllzz** [comment]
I was unable to find something wrong with our Api or the Unity implementation of it.
Can you also try pushing scores to a different table maybe and see if the issue continues there?

**Comment by ghost** [comment]
@nilllzz Here's the full file from which the snippets are
```cs
using UnityEngine;
using GameJolt.UI;
using GameJolt.API;

public class GJAPIHandler : MonoBehaviour {

    public bool isSignedIn = GameJoltAPI.Instance.HasSignedInUser;
    private int tableID = 428009; // Set it to 0 for main highscore table.
    public Spawner spawner;
    const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    public string GuestName = "Guest ";

    private void Awake()
    {
        for (int i = 0; i < 10; i++)
        {
            GuestName += chars[Random.Range(0, chars.Length)];
        }
    }

    public void SignIn() {
        isSignedIn = GameJoltAPI.Instance.HasSignedInUser;
        if (!isSignedIn)
        {
            GameJoltUI.Instance.ShowSignIn();
        }
    }

    public void SignOut()
    {
        isSignedIn = GameJoltAPI.Instance.HasSignedInUser;
        if (isSignedIn)
        {
            GameJoltAPI.Instance.CurrentUser.SignOut();
        }
    }

    public void ShowLeaderboards()
    {
        GameJoltUI.Instance.ShowLeaderboards();
    }

    public void addScore()
    {
        isSignedIn = GameJoltAPI.Instance.HasSignedInUser;
        if (isSignedIn)
        {
            Scores.Add(spawner.score, spawner.formattedTime, tableID);
        }
        else
        {
            Scores.Add(spawner.score, spawner.formattedTime, GuestName, tableID);
        }
    }
}
```
I am now going to test using a different score table and I'll reply once I've confirmed if that works

**Comment by ghost** [comment]
Tried making a new table, that one didn't work either

**Comment by nilllzz** [comment]
Resolved.
