### ISSUE TITLE
Forum main page always gives server errors

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1284]
Everything works, even the forums, except for the general page. Whenever you click it it will seem for a long time nothing happened at all, and you may even try other links and they work until suddenly you get the server error page. Topic overviews, posting stuff on the forums, even editing stuff appears to work fine, only the main page doesn't (or at least the link to it). This happens from the pull down menu, as well as from links inside the forum itself. 

All other pages I tried to so far work normally.

**Comment by Tricky1975** [comment]
![image](https://user-images.githubusercontent.com/11202073/59975264-c698cd00-95b6-11e9-9623-f1a8fd6f2f7a.png)

![image](https://user-images.githubusercontent.com/11202073/59975272-d7494300-95b6-11e9-98bd-1e0edcb87960.png)

Also clicking notifications directing to the forums says "Oh no! Couldn't go to notification!"

**Comment by YLivay** [comment]
Forums were disabled temporarily. It'll come back hopefully in a day or so.
