### ISSUE TITLE
Identing is removed in code blocks

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1285]
![image](https://user-images.githubusercontent.com/11202073/59975235-2e024d00-95b6-11e9-9110-baa08965e632.png)

In this demonstration Lua code (in which I demonstrated how to write a stacking routine yourself if a programming language doesn't support it. Hey it's not relevant what Lua supports itself, I was just demonstrating the technique itself, okay) I did indent the code in my functions, but as you can see, Game Jolt removed it all.

**Comment by YLivay** [comment]
Was this a new post or did an old post you have get it's indentation removed?

**Comment by Tricky1975** [comment]
A new post,... You may not find the post yet unless you use your admin powers to "hack" the system, as this is part of a blog of mine that is still scheduled, but I posted this issue, immediately after I created that blog page, 

Now a funny thing to note on my programming language NIL which I posted on Game Jolt yesterday, were this bug now takes odd forms.

- [On the normal Game Jolt Page](https://gamejolt.com/games/NIL/421723) you can see when you examine some example code written in NIL that all idents have gone.
- [On the Game Jolt Site](https://tricky.gamejolt.io/nil/) where the same data is used, the idents are suddenly there, although I'm not sure if the sites are not bugged, or if it's because I didn't edit that description anymore since @nilllzz fixed the bug not showing the page's content.

**Comment by nilllzz** [comment]
Ok, I confirmed the problem exists.
At least all the data is still there, the CSS setup of the site is just not displaying the spacing if it's done with space characters (tabs would work).
I'm gonna see that I can re-enable that.

**Comment by nilllzz** [comment]
Alright got it fixed, will go out later today. No action required from your side, the spaces will appear :)

**Comment by Tricky1975** [comment]
Thanks for fixing that so fast. Question... My GJSite page of NIL is now only a blank screen. Will that also be back once the fix has been pushed?
