### ISSUE TITLE
Game Jolt sites not updating when content should be changed

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1287]
Let's explain it with the link to my newest project page for the project [NIL](https://tricky.gamejolt.io/nil/).

As you can see, it only shows the download gadget, and nothing more. I did use a default template, and the gadget to show the same content as on the actual [Game Jolt Page](https://gamejolt.com/games/NIL/421723), but it's completely ignored, very likely the result of the latest feature enhancements.

**Comment by YLivay** [comment]
I think there's a few minutes cache on templates. Does it still happen?

**Comment by nilllzz** [comment]
Fixed :)

**Comment by Tricky1975** [comment]
Thanks, Nilllzz ;)
