### ISSUE TITLE
Clicking the upload media button in a comment form submits the form

### ISSUE THREAD

**Issue by nilllzz** [gamejolt/next-issue-tracker#1289]
On Mac/Firefox (latest) the comment reply form gets submitted when pressing the Upload Image button in the block level controls.

**Comment by YLivay** [comment]
Do we even have a plan to tackle this one?

**Comment by YLivay** [comment]
We have a potential, very non obvious fix ready to be pushed out.
When deployed - contact the reporter to verify the fix.

If it's what I think it was I don't know why it ever worked in the first place. I'm so confused.

**Comment by YLivay** [comment]
we may have fixed this.

**Comment by nilllzz** [comment]
Fixed.
