### ISSUE TITLE
Genre links do not work in "Hot Games"

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#129]
I've tried searching, as well positive and negative and that works as well as the filters, but the genres return me a "Page not found" error.

**Comment by Tricky1975** [comment]
Supplement: I tried the genre links on the other sections too and there I get the same error as well.

**Comment by acidpoison** [comment]
Yup, I'm getting this too. In Chrome, if I go to a genre page, close it, and re-open it using the ctrl+shift+T shortcut, it gets a Page Not Found.

**Comment by hworld** [comment]
K, I'll get that fixed tomorrow. I'm sure it's a minor bug. I pushed it out quickly for testing before I left the office.

**Comment by hworld** [comment]
Fixed.
