### ISSUE TITLE
Non-Existent user follows me

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1291]
I got the notification this morning that a certain user follows me, but when I click the notification I get a page not found. Now I won't mention the user out in the open, but judging the kind of username, it was a porn spammer or porn malware spreader or somebody having a porn bio, well anyway, somebody who was banned for something related to sex, and the ban caused the bio to disappear (since I no longer am a mod I cannot check that anymore), but the notification did not disappear. 

Maybe for me that much of trouble as a former moderator, and since the name of this user gives me an indication why a ban was issued, but I think for people who were never involved in the staff this can lead to awkward situations, like confusion, and especially when people got their account removed by their own request we should make sure notifications like these cannot linger somehow.

**Comment by YLivay** [comment]
Yup, thanks for reporting. This is a bit of a tricky one to solve (pun not intended). These should go away when users are fully purged but they don't for users that were just soft banned.

TODO list ++

**Comment by Tricky1975** [comment]
My nickname is "Tricky" for a reason :P

**Comment by nilllzz** [comment]
Fixed.

**Comment by Tricky1975** [comment]
In other words if a user follows me who gets banned/deleted the notification would just disappear from my notifications list (and also from my followers list?)

(And why did you re-open this issue... Still something wrong?)
