### ISSUE TITLE
Can't edit overview/setup on gamepage

### ISSUE THREAD

**Issue by juggernautofmc** [gamejolt/next-issue-tracker#1294]
**How are you using Game Jolt?**
- GameJolt Client
- Chrome (windows)

**Please describe the issue you are having**
Whenever I go to manage game to try add more images to my gamepage, change the description, or upload builds now it doesn't let me. In fact, it doesn't provide me with the OPTION to do that. I own this game page, so it wouldn't be that I got removed from a collaborator list. I'll show a screenshot to show what I mean.
![problem](https://user-images.githubusercontent.com/20804179/60190728-fd095e80-97e7-11e9-91f0-6849e2b1f933.PNG)

**Comment by nilllzz** [comment]
Hey, sorry about that.
We found the issue on our end and are fixing it.

I'll report back here once it's live.

**Comment by juggernautofmc** [comment]
I thank you sincerely for responding promptly, I was worried it was going to take much longer, so thank you.

**Comment by nilllzz** [comment]
Alright, the fix is deployed! You should be able to access all features of your game again :)
