### ISSUE TITLE
comment miscounting

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1295]
When I take a look on my game [Cynthia Johnson](https://gamejolt.com/games/cynthia/294717) (this only counts on the moment I wrote this as I don't know how things are now), I only see ONE comment, yet the system says there are 3.... where are the other 2? Deleted by me as a dev or as a mod, or by the comment themselves... either way, 2 more comments counted then there are, whatever the reason is...

**Comment by nilllzz** [comment]
Those two comments had their parent thread removed, while the comments themselves are still active.
Currently, this is expected behavior.

**Comment by Tricky1975** [comment]
Ah, that explains a lot... You gotta forgive me that this works quite confusing... :)
