### ISSUE TITLE
Can't delete shout messages

### ISSUE THREAD

**Issue by TruddyTheDuddi** [gamejolt/next-issue-tracker#1296]
When I try to delete a comment from my shouts, I can't and it sends the following error message in the console:

It comes from a file called comment.ts (a **try** throwback if I remember correctly), along with a Payload error Error: "Request failed with status code 403"

I've tried both Chrome and Firefox, both of them are unable to hand the request.

<img width="661" alt="Screen Shot 2019-06-28 at 7 38 45 PM" src="https://user-images.githubusercontent.com/47558258/60360690-97ca8e80-99dc-11e9-87c8-40fbd6e9f366.png">

**Comment by nilllzz** [comment]
Will take a look.

**Comment by nilllzz** [comment]
Should be fixed :)
