### ISSUE TITLE
Emebedding YouTube videos does not work

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1298]
**How are you using Game Jolt?**
Browser. Firefox -> Win10

**Please describe the issue you are having**
I only tried this on the forums so far and so far only with YouTube videos and not with other stuff, but when I use the embed feature to include a YouTube video, the embed simply disappears from my post, and nothing is shown, and when no description is added, it just ends up with an empty post.

**Comment by YLivay** [comment]
Can you link the url you pasted for the youtube embed? I can't recreate this

**Comment by Tricky1975** [comment]
I don't remember which video I used, but I do recall I tried this with ID-only, full URL, anything, but all resulted into what happened to me above.

**Comment by YLivay** [comment]
Does this happen consistently for you? Was it a specific url or just in general its bork for you?

**Comment by Tricky1975** [comment]
I shall try it again later, and set things up step by step... Since I've seen more people post links to YouTube rather than embedding (at least on the forums) it does seem I'm not the only one who suffers.

**Comment by Tricky1975** [comment]
Now I'm writing a (scheduled) blog about Sound Tracker and tried to embed this video ( https://www.youtube.com/watch?v=5ywaCR5Tg4A ) also only to have it automatically removed immediately after saving my draft.

**Comment by Tricky1975** [comment]
I think I know what caused this to happen, and if so I (and tons of people with me) were being stupid. Pressing Enter after copying the URL to the WYSIWYG editor, may look obvious, but it appears it was not. I guess we are all a bit spoiled with systems who only account for copy-and-paste and therefore pick things up automatically, or that we are spoiled thinking that pressing "send" picks everything up. The way most GUI systems work, the latter seems most likely, so I never press enter after entering data, since that would mostly send my entire form (pre-maturely).

So at least I can conclude that this is not a true bug, but still something that will need to be looked at to prevent confusion for future members in the future. Either a clear statement that you need to press enter or (which may even me more common) a kind of pop-up, that people MUST confirm with either Enter or an "OK" button, before they can even continue to type their comment/forum post/blog/whatever. That or making sure that the clicking the "Send" button automatically confirms all open embedding requests before actually sending.

Should this remain an issue, or is it better to close this and convert this into a suggestion on gj-improve?

**Comment by nilllzz** [comment]
Yeah, make a gj-improve about it. I think I would gravitate towards a little hint that says "press enter to insert" or something.
