### ISSUE TITLE
Clicking "Gif" leaves the focussed typing field as the comment box, behind the gif selector

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/next-issue-tracker#1306]
When you click the gif button, the focused text field doesn't change to the search bar, it remains as the comment box which is hidden completely by the gif selector. So unless you notice and click into the search bar, your search gets typed into the comment box, which is behind the gif selector.

It would be nice if clicking gif automatically put the search bar as the focused text element.

This happens when writing a comment and probably other text fields like posts or descriptions but I've only tested it in comments.

**Comment by YLivay** [comment]
we know about this one, it's in our list

**Comment by hworld** [comment]
This drives me nuts as well. Maybe we should prioritize it to be done before other stuff.

**Comment by nilllzz** [comment]
Fixed.
