### ISSUE TITLE
Able to chat after logging off

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/next-issue-tracker#131]
After I log off, I can still chat with friends. Could cause a potential issue if you have a jerk friend who says rude things to your gamejolt friends. :(

![1](http://i.imgbox.com/bHaUVBHT.png)
![2](http://i.imgbox.com/ZOR8izXn.png)

**Comment by hworld** [comment]
Can you try this on the current site and see if it's also possible there?

**Comment by acidpoison** [comment]
Nope, on the normal site, all the friend chats close when you log out.

**Comment by hworld** [comment]
This should be fixed now. Reworked so the whole interface watches for a log off and updates all the components accordingly.
