### ISSUE TITLE
Issue with upploading the thumbnail

### ISSUE THREAD

**Issue by Kuzuru** [gamejolt/next-issue-tracker#1314]
**How are you using Game Jolt?**
I'm DEV

**Please describe the issue you are having**
when i'm tryin to upload my thumbnail (1280*720; 725kb) i have this:
![image](https://user-images.githubusercontent.com/49472529/61725036-7e70f400-ad88-11e9-860c-ba4d84867887.png)
![image](https://user-images.githubusercontent.com/49472529/61725046-8335a800-ad88-11e9-955b-39e4ecd40c94.png)

**Comment by Kuzuru** [comment]
It uploads, but after It write "Processing" I get an error

**Comment by YLivay** [comment]
Hey, can you share a link to the game you are trying to upload to? your dashboard link is also ok if the game isn't published yet :)

**Comment by KUZURUTK** [comment]
I can not give you a link to this game, as it is hidden due to the fact that I need to upload a thumbnail, lol

**Comment by KUZURUTK** [comment]
oh... wait..

**Comment by Kuzuru** [comment]
https://gamejolt.com/dashboard/games/428207/

**Comment by YLivay** [comment]
Thanks! I'll check it out real quick

**Comment by Kuzuru** [comment]
kk, thank you

**Comment by YLivay** [comment]
Woah seems like the connection of one of our webservers to our storage server is having a bad day. Sorry about this, I hope it won't take more than a couple hours to fix. I'll update here :)

**Comment by Kuzuru** [comment]
okay, i'll wait

**Comment by YLivay** [comment]
This should work again, thanks for reporting :)
