### ISSUE TITLE
Invisible avatar

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1315]
![image](https://user-images.githubusercontent.com/11202073/61903849-d3963c80-af25-11e9-8535-ccf647e59e23.png)

Same user, same avatar, but the big one is one white field while the smaller version is clearly visible. I wonder how this is possible. (FireFox on Windows 10).

**Comment by nilllzz** [comment]
It's because the background on the larger avatar is pure white, and the avatar itself is only white and transparent. Not a bug.

**Comment by YLivay** [comment]
Should the background be white on this actually? Seems like wed want a transparent background in the header too yeah?

**Comment by nilllzz** [comment]
We don't use a transparent background in the feed user avatars, they are bg-subtle.

**Comment by Tricky1975** [comment]
Still I think a consequent color for avatar backgrounds would do well, especially for avatars using transparency...
