### ISSUE TITLE
Editing fireside posts requires processing that sometimes lasts eternally

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1317]
**How are you using Game Jolt?**
Firefox for Windows 10

**Please describe the issue you are having**
![image](https://user-images.githubusercontent.com/11202073/62411526-7e78bb80-b5f4-11e9-9b3d-162387240685.png)
When I click "edit" on a FireSide posts that needs some correcting, I get these dancing guys to indicate some loading or processing or whatever, and they keep on doing it until.... I dunno, the Armageddon, maybe? Now this time it handles an article that has been scheduled for a month or so, but I've also been through this before on articles that were already public and in which very big errors (and then I'm not talking about typos or grammar mistakes, but really big errors that had to be fixed IMMEDIATELY), and then not being able to edit them is downright frustrating and even unacceptable (in my case it didn't cost me any money, but I can imagine the damage could be great if this would happen on a marketplace game devlog, if some wrong data about pricing or discounts is not fixed on time), and just quickly pinning a comment with rectifications under that is NOT a solution. It's both unprofessional, and overall ignored by 99% of the visitors of the blog, so the damage still be done. 

(SUPPLEMENT: Refreshing the page will NOT fix this issue).

**Comment by YLivay** [comment]
This is happening consistently for you?

**Comment by YLivay** [comment]
Working perfectly fine for me on firefox and chrome on both pc and android.

**Comment by Tricky1975** [comment]
It's pretty random... some days this works, and some days, this takes an eternity,
I've had this for quite a long time now, as I've also had this issue back in my Mac days using Google Chrome. It can't be my ISP, since I've had this issue also with two different ISPs.

**Comment by Tricky1975** [comment]
Supplement: Now it works, and I can instantly get onto editing, but experience from the past taught me that it's not a matter of "if" this happens again... but rather "when"...

**Comment by YLivay** [comment]
It sounds like just network issues, unreliable internet connection. It seems to work consistently on my end so it doesn't seem to be an issue on the server's end. Do you have any browser extensions? Are you on a wireless connection?

If you want, you can try opening the devtools (ctrl+shift+i) and go to the network tab while trying to edit your post. you'll be able to see if any request is failing - basically anything that goes to gamejolt.com that does not have a status code of 200-299.

**Comment by Tricky1975** [comment]
If I suffer like this again, I will certainly do so.
- My main computer system (which I use for 99% of my game jolt activities) is just wired to my modem
- My old ISP used cable technology (same net work used for analog TV), my current ISP goes over an ADSL connection over the fixed telephone network. So two completely different kind of technologies...
- Well and I said it before, but I'll say it again for summary reasons. I had this on:
    - Chrome on Mac
    - Firefox on Mac
    - Firefox on Windows 10

Well when it happens again (may take awhile since I don't edit FireSide posts every day) I'll check the data (even screenshot it if I must), to see what evil lurks there.

P.S. Game Jolt is the ONLY site in which I ever experienced these kinds of issues, and I've been on the internet since the late 1990s.

**Comment by YLivay** [comment]
Not related to this issue specifically, but we might be adding some logging for failing requests to help us find and tackle anomalies where requests straight up don't reach our servers for some reason.

I'm closing this issue for now, if you encounter this again lmk and i'll reopen.
