### ISSUE TITLE
devlog hp length does not update when edting draft

### ISSUE THREAD

**Issue by iamdavidsen** [gamejolt/next-issue-tracker#1318]
**How are you using Game Jolt?**
Posting updates to my game.

**Please describe the issue you are having**
When saving a devlog as a draft and then edit it. the HP slider does not update when typing the devlog.

Reproduce:
1. Create devlog with some text (the HP update as it should)
2. Save as draft
3. Edit the saved devlog
4. Type in the devlog and see the HP slider is not updating anymore

![Image of Error](https://tunawithsalmon.nyc3.cdn.digitaloceanspaces.com/images/noupdatehp.PNG)

**Comment by YLivay** [comment]
Confirmed, only happens for draft posts wat.
Thanks for the report!

**Comment by nilllzz** [comment]
Fix going out now.
