### ISSUE TITLE
APK Files "corrupted"

### ISSUE THREAD

**Issue by PhotoNegativeMickey** [gamejolt/next-issue-tracker#1320]
**How are you using Game Jolt?**
Posting a build/release of an Android port

**Please describe the issue you are having**
I'm attempting to post an android port of a game I made called "Dodge the Projectiles 2" and upon uploading the APK it detects it as corrupted. It's easy to tell this is on Gamejolt's end as I sent the file to my phone to test out and it did work. I uploaded an APK file before so I think something got messed up in the coding.
![image](https://user-images.githubusercontent.com/54124424/63063857-4f1c5580-bef6-11e9-8adc-b0e6cffb6ec8.png)

**Comment by YLivay** [comment]
This has been solved :)
