### ISSUE TITLE
Portfolio sites

### ISSUE THREAD

**Issue by TruddyTheDuddi** [gamejolt/next-issue-tracker#1326]
### Portfolio sites
So first of all, I'm disappointed to see that only a few people use this feature. It's really a huge one, and Gamejolt should be promoting and encouraging users to set their portfolio up!

However, I've come across two bugs:
- When I'm using a template and I click on **Customize Theme** or **Edit Content**, it sends me to a blank page (about:blank). I'm using Firefox and on a Macbook. Yet, when I click on **View site**, it opens the portfolio perfectly.
- When I upload my own folder with my website, if I don't have any file called "index.html", the uploader crashes and sends me to a GJ error page without giving me any warning.

**Comment by Tricky1975** [comment]
Yeah, I think most people don't know the feature exists, which is a bit of a bummer, I think.

**Comment by TruddyTheDuddi** [comment]
A script blocker browser extension was blocking it and didn't launch. Looks like it works fine!
