### ISSUE TITLE
Odd issue. Rename this if you have a good name

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1327]
**How are you using Game Jolt?**
Browser

**Please describe the issue you are having**
Suddenly when I tried to get into the fireside posts on my profile I got this:
![image](https://user-images.githubusercontent.com/11202073/65729660-63d83580-e0bf-11e9-918b-836333e77acc.png)

Now I cancelled that, but it gets worse. Now every action I do will get interrupted by that "download" request, even on different sites, and even different tabs, even blocking out my browser activity completely (I even used Chrome to post this issue while I normally use FireFox, as FireFox keeps popping up that download request as I tried to reach github to write this issue).

**Comment by YLivay** [comment]
I'm fairly certain that's not an issue on our end, especially if you're having it on other sites as well. Do you have any weird extensions? Are you using a proxy that perhaps rewrites some headers?

**Comment by Tricky1975** [comment]
The issue is that I clicked a link on Game Jolt, which then kept haunting me on all sites. The file to download was always "@Tricky" and the "from" field was always "gamejolt.com" 
I think it's obvious that I opened my own profile when this happened. I eventually shut down Firefox and reran it and the issue stopped. I am not aware of any proxys, that my ISP could be using. I myself am using using the internet as my ISP delivers it. And it just kept repeating itself with the same file from gamejolt.com over and over and over. I kept clicking cancel and the close icon, only to have it back all the time. I didn't try to see what I'd get if I actually clicked the "OK" button though.

**Comment by YLivay** [comment]
It really sounds like a browser issue. We do absolutely nothing special in that page, or in any, and nothing changed recently that may have caused this in any way. In fact, nothing changed at all in the past week or so as we haven't pushed any of the stuff we're working on yet. Sorry, I don't think this is related.

p.s. I wouldn't be surprised if its just Mac going to the gutters. It's on a steady course already, yeah?

**Comment by Tricky1975** [comment]
> I wouldn't be surprised if its just Mac going to the gutters.

I actually WOULD be surprised if this was a Mac issue, since I'm using Windows 10 now

**Comment by YLivay** [comment]
Hey, hey.. listen.. Mac's so bad it might just be possible.
Anyways, im going to close this issue, browser resubmitting requests is a browser specific behaviour, and these requests resulting in a download isn't anything we set on our end anywhere.

**Comment by Tricky1975** [comment]
"these requests resulting in a download isn't anything we set on our end anywhere."

No? Then I wonder how come that when I enter the url of any uploaded pictures the system always forces me to download them in stead of viewing them (happened on both Mac and Windows and on ALL browsers I tried).

**Comment by YLivay** [comment]
Uploaded pictures have literally nothing to do with the request page that was attempting to download in the screenshot you pasted, and is completely fine if it attempts to download tge images...

As for the page - which is what this issue is about - I cant explain why something happens specifically on your setup. Its not anything that exists for anyone else and is not something we set on our end anywhere. You can "blame the engine" as many times as you want but it gets us nowhere. Check you setup. Nothings changed on our end - this topic is closed..

**Comment by Tricky1975** [comment]
Easy, huh? I remember this issue before on a Linux computer on a complete different location (that computer was not even mine). Guess the site... But have it your way... I'm just as sure about the case as you are, but I guess the site owner is always right (even when he's not).

**Comment by YLivay** [comment]
Think we can arrange a remote control session so I can see that issue for myself? I'll probably have to do some live debugging to figure out why the hell this happens, especially if you say it happens on multiple different devices in different locations.

**Comment by Tricky1975** [comment]
It happens too randomly for that, unfortunately, and I don't know how long I gotta wait for this to happen again. All I can do is hope for when it happens again that something like this would be possible to do, as you would be on-line then. I've worked with programs like TeamViewer before, so that is not really the issue. The occasions are not even very much, but when it happens the results are great, and for me resetting my browser was an obvious thing to do, but for the majority of people... I guess it's not...
