### ISSUE TITLE
Hyphens in channel names = NOT WORKING

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1330]
Copying this portion from the forum post by FreezerNick demonstrates what I mean

![image](https://user-images.githubusercontent.com/11202073/66496000-7b012500-eaba-11e9-9460-707b957b0bfb.png)

However this issue is not limited to the forums alone, but to comments, as well. I've never tried FireSide posts, but I'm pretty sure the issue lives there too.

**Comment by nilllzz** [comment]
That's a hashtag, not a channel name.
If you want to not have it linked, put it in an inline code like this: `#gj-help`

**Comment by Tricky1975** [comment]
Hashtag or channel name, fact is that it doesn't work, and this is a bug, which has actually been present for ages....  Feel free to change title if you like... The channel name (this is a forum channel. You called it that, not me, as that name is faulty as far as forums are concerned) is #gj-help and not #gj, but that's how the auto detector translates it and auto-links it and will also put it in the tag database in the items where that counts.

**Comment by nilllzz** [comment]
It is not a bug, because this is not a channel name, it is a hashtag.
Hashtags only allow alphanumeric characters and underscores.

It auto-links it to go to `/search?q=#23yourtag`, which is a search page based on tags on games, users and posts.

Just because the hashtag was used in a forum post doesn't change its context to a forum channel, they cannot be addressed via autolinking. That's why I said, if you want it to not autolink to a tag search, mark it as inline code.

**Comment by Tricky1975** [comment]
Then why are all forum boards prefixed with a # in the first place causing this to happen? Hm!
No matter how you put it, don't deny this is not be possible... If that doesn't fill your definition of a bug, then what does?

**Comment by nilllzz** [comment]
iirc the `#` was put there as a nod to markdown, since that is what denotes a header.
Looks kinda like a hashtag too.

But yeah, this is not a bug as it's intended behavior.
I explained how we decided on how the autolinking after a `#` character works, which works as intended, at least in your example: `-` are not allowed in hashtags.

**Comment by Tricky1975** [comment]
Then you should still rename gj-help, gj-improve, etc..... Every time people refer to those this issue happens.... The half links will always get up there, so if that is intended behavior I see you see fit in a site that shows stuff that nobody (in their right mind) would expect. I don't deem that intended behavior I deem that (and the closure of this ISSUE THAT IS AN ISSUE whether you recognize it or not) laziness.... If that's the path you intend to follow find with me, but at least be honest about it that you seek to confuse the crap out of people with "intended behavior" that nobody would expect, and will work confusing due to wrongly set up auto-links....

**Comment by nilllzz** [comment]
Please refrain from gaslighting, this can be discussed in a civilized manner.

And no, you are not _supposed_ to be able to link to a channel by typing its name with a `#` in front of it. The notation in the channel list doesn't really have any meaning.

We even made it so when you are writing a post, it previews which links get autolinked, so there is no ambiguity whether or not a hashtag will work before you submit the post.

I guess a thing I can bring up would be to remove the `#` from the beginning of the channel names. I think those have just been there forever and don't really serve a specific meaning.

**Comment by Tricky1975** [comment]
They have been there since the Game Jolt Next update actually, and yeah since I was here before that update that, I know.... Actually to be more precise when the forums were adapted to GJ Next, and that was around the same time the #tag system actually came here.... Back then I already wondered what those prefixes that were never there before were for, but as I saw tags coming up, and seeing how discord uses the # for channel prefixes, I came to see a relation... In the end they appear never to be used, and now lead to this issue....

If you don't recognize the facts as they are irrefutably smeared in your face, fine, have it your way.
What is the point of having an issue tracker if you're not gonna take the bugs reported seriously anyway is the discussion I then have to bring in.... 

And if you consider me rude, then lemme state this... I'm always rude when people are rude to me... It's my way of survival... And I am also ONLY rude when people are rude to me, overall (and then I mean really rude, not joking around taken up wrongly). But if you want then then I apologize that I ever considered to help you. That was a true act of evil.... Geesh... Yeah, you pissed me off, you can tell, right... It's kinda frustrating when many points you bring in are not taken seriously at first only to be proven right in 99% of cases afterward, and be deemed an arrogant git when even Donald Trump cannot refute the evidence anymore (or even try to).  No matter how you put it, this is a bug, or otherwise behavior that leads to posts looking like they should not, causing ugly forum posts or confusion.... 

But hey, GJ is not *my* site... So if you don't wanna fix something that is an issue, that's maybe not my case. One one thing I can never stand is when people make up excuses in order not to take me seriously. Doing then and then saying "we can discuss this in a civilized manner" is one way to insult me... Also one of the reasons I kicked my old man out of my life for... I don't take that from anybody, and also not from you.

**Comment by nilllzz** [comment]
It's just that the tag system was never intended to function together with forum channels. That they are prefixed with the same character as a tag is pure coincidence.

The tagging system is working as intended: They do not accept `-` as a valid character. Since they are not supposed to work with channels, having dashes in them is not a requirement for them to function as intended.

What you perceive as a `bug` is a misunderstanding of the intended design. I guess that having the tags in front of forum channels is slightly misleading, and as I said, I can try and remove them from there, they don't really serve a purpose.

As a little trivia: The rules for which characters are accepted in a tag is copied from Twitter. They don't allow dashes, so we don't either haha.

**Comment by Tricky1975** [comment]
Fine, at least we've agree then that the '#' lead to odd situations... Forum channel being addressed by # and not working or '#' being misleading when not serving a purpose comes at least down to that there's at least an issue. If you could have said that from the start you could have saved me some adrenaline.... Luckily playing DOOM only with the intention to kill kill kill, was always a good way for me too blow off some steam.... 

Perhaps I overreacted a little, as I am currently in a very bad mental condition... I must admit that... If so I apologize for that, but still, I stand by what I said... This *is* an issue.... a misleading '#' is what I still see as something undesirable...

**Comment by nilllzz** [comment]
I never really noticed those tags, but yeah they don't make sense.
I'll leave this closed but make an internal note and might remove them soonish.

> Perhaps I overreacted a little, as I am currently in a very bad mental condition... I must admit that... If so I apologize for that, but still, I stand by what I said... This _is_ an issue.... a misleading '#' is what I still see as something undesirable...

And yeah it's alright man, I am not phased by it. You know me :)

**Comment by Tricky1975** [comment]
Perhaps, but I hope you understand the situation also from where I stand. I don't want to use it as an excuse, but I've been haunted all my life with not being taken seriously, and having to take the blame when trouble arises that could have been prevented when they did take me seriously from the start. Thank Kitty (my cat) for getting a bit more of my calm... She hopped onto my lag and made me realize this trauma was getting to its worst this week and that I was a bit in overheat mode... Not your problem, but at least I hope that by knowing this, you can understand my position in things like these...

**Comment by nilllzz** [comment]
Yeah you're good. Other people might get offended, but I really don't. Hope you're doing better soon mate.
