### ISSUE TITLE
New post action button appearing even when user not logged in

### ISSUE THREAD

**Issue by TruddyTheDuddi** [gamejolt/next-issue-tracker#1332]
<img width="718" alt="Screen Shot 2019-10-10 at 5 52 35 PM" src="https://user-images.githubusercontent.com/47558258/66585390-03e59280-eb87-11e9-88b2-80585046e2fd.png">

The 3 "more" dots are still there when I'm not logged in and when I click it to expand nothing shows up in the menu.

**Comment by nilllzz** [comment]
Fixed, thanks for reporting :)
