### ISSUE TITLE
youtu.be links in embedding rejected

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1347]
When trying to embed youtu.be urls are rejected.
(YouTube cheated a little, as .be means the domain has been registered in Belgium... oh well).

I do consider this not desirable behavior for a very important reason, and that is that YouTube presents these urls when you click the "Share" link under each video and when you let YouTube itself copy and paste the video URL to the OS's clipboard. And personally I always advice not to touch the url bar on top of the browser when you are not sure what you are doing... So one way or another, I think YouTu.be urls should be supported too...

**Comment by YLivay** [comment]
They are supported. Can you paste the exact url you tried with?

**Comment by Tricky1975** [comment]
I've tried this several times on several moments and they were never accepted when I used the embed feature (At least not in the WYSIWYG editor of the devlogs)....

This one https://youtu.be/aAoT59Uwk8s is the last one I tried (where this one https://www.youtube.com/watch?v=aAoT59Uwk8s leading to the same video was accepted).
