### ISSUE TITLE
Guest score entries are missing data in scores list.

### ISSUE THREAD

**Issue by MausGames** [gamejolt/next-issue-tracker#135]
![avatars_missing](https://cloud.githubusercontent.com/assets/6109189/6413691/6b75090c-be92-11e4-9147-c744fb15b266.png)

Also there is no indication for a *guest*, except the missing link on the name.
Screenshot from: http://wttf.gamejolt.com/games/disco-rock/18996

**Comment by hworld** [comment]
Fixed.

We now show (guest) tags like the current site and show the ninja for guest avatars.
