### ISSUE TITLE
can´t download anything

### ISSUE THREAD

**Issue by kraken131004** [gamejolt/next-issue-tracker#1361]
I use the website of gamejolt and since I sign up I cant download neither the gamejolt client or any games, the download just dont start even with the google configuration, I could download some games but not anymore please help

**Comment by HTMLjsgit** [comment]
Me too!
help we.........

**Comment by ghost** [comment]
Same... Gamejolt is broken

**Comment by Gonee-chan** [comment]
Neither i can

**Comment by hworld** [comment]
This should be fixed now.
