### ISSUE TITLE
No comment body in email notifications

### ISSUE THREAD

**Issue by niksudan** [gamejolt/next-issue-tracker#1362]
Previously, emails would show the body of a comment. Now, only the title appears at most. This happens for all types of comment.

![image](https://user-images.githubusercontent.com/6004491/75096615-49848400-5599-11ea-9bfb-15c61ae0a795.png)

![image](https://user-images.githubusercontent.com/6004491/75096638-7e90d680-5599-11ea-8042-0d3ed5fc5679.png)

**Comment by hworld** [comment]
This was on purpose because of spammers and harassers. Makes it harder to shove unwanted content in people's faces. Maybe we can add it back for certain scenarios, like it you're friends with the person.

**Comment by niksudan** [comment]
At the end of the day, the user is going to be seeing that content when they visit the website to address these notifications. It’s just delaying the inevitable.

There could be ways to prevent certain types of content:

- Make it rich text only, so any images aren’t shown (preventing any inappropriate imagery)
- Truncating the body to prevent walls of text from being displayed
- Have an option on-site to disable comment bodies in emails

The only instance where emails do not show message content I can think of are banking websites, which do it for security purposes. Other social websites will let everything through.
