### ISSUE TITLE
Unable to download game using Chrome. Firefox works.

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/next-issue-tracker#1363]
The download for this game:
https://gamejolt.com/games/UndertaleYellow/136925
fails to start using Chrome(80.0.3987.116). It works on Firefox(73.0.1)

Screenshot from Chrome console: https://i.imgur.com/YGk6ppt.png

**Comment by nilllzz** [comment]
The domain in the console screenshot is most likely ads being blocked.
I am able to download the linked game in both Firefox and Chrome (80.0.3987.106 and 80.0.3987.116).

**Comment by NathanAuckett** [comment]
Pretty sure @YLivay fixed it. Was something to do with being unable to initiate a download through an ad frame.
https://www.chromestatus.com/feature/6311883621531648

I think you can close this one.
