### ISSUE TITLE
It just doesn't let me download

### ISSUE THREAD

**Issue by 4BZ0RB** [gamejolt/next-issue-tracker#1364]
**How are you using Game Jolt?**
On my laptop (not a Chromebook) on Chrome (I'm on Windows OS)

**Please describe the issue you are having**
I click the "Download for Windows" button and it doesn't do anything. I've checked my folder multiple times to see if anything happened. Maybe I'm just stupid and I'm doing something wrong, but it just doesn't work. This is different from the other one where it wouldn't download, because I don't get an error message or anything. When I click the button it does nothing.

**Comment by YLivay** [comment]
What are you trying to download? A game? our client?
We had an issue with downloading things on chrome 2 days ago. We resolved the issue for downloading games but haven't fixed downloading the client yet.

**Comment by YLivay** [comment]
Fixed

**Comment by 4BZ0RB** [comment]
Downloading the client is what doesn't work

**Comment by 4BZ0RB** [comment]
Which it now does

**Comment by nilllzz** [comment]
@4BZ0RB It does work now? Meaning you can download games through the client now?

**Comment by 4BZ0RB** [comment]
Yes

**Comment by YLivay** [comment]
@nilllzz you dope, the issue was downloading the client from the client landing page. it was the same issue we had with downloading games earlier, only we didnt fix it there haha.
Anyways, glad to see its resolved, gonna close this issue :)
