### ISSUE TITLE
Problem with games showing up

### ISSUE THREAD

**Issue by JacobWalrath1** [gamejolt/next-issue-tracker#1365]
For some reason, some games I try to look at only show up in a google search. If I look up the person who created the game on GameJolt then go to the games they made, it does not show the game. If i search it up on google, it shows up and when i click on it, it will show the game. This means I can't download some games off of the client which is what i want to do.

**Comment by YLivay** [comment]
can you link one of those games? google results may be slightly outdated, but you shouldn't be able to view a game that is not normally shown on GJ.

**Comment by JacobWalrath1** [comment]
Here's some games I found that don't appear in gamejolt.
https://gamejolt.com/games/finalhours/205264
https://gamejolt.com/games/FNaTI-TC/317116

**Comment by JacobWalrath1** [comment]
I figured it out. The games were hidden meaning that they could only be found through links, or something.
