### ISSUE TITLE
issue refert to the architecture

### ISSUE THREAD

**Issue by 4dr0s5** [gamejolt/next-issue-tracker#1366]
Pleas people if you research this package for linux, don't make the client platform only for 64 bit processor, there are still many 32 bit machines in the world & this is the perfect project for that PCs, you know that, thanks for reading me

**Comment by YLivay** [comment]
While it should be relatively make 32 bit linux versions (and maybe even osx?), there just isn't enough justification to do it. we don't want to have to maintain it at this point in time.
