### ISSUE TITLE
Clear rating button in odd place

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/next-issue-tracker#138]
On small resolution computers, the clear rating button appears over the voltage bars.

![bugss1](http://i.imgbox.com/uRG265gd.png)
![bugss2](http://i.imgbox.com/qI3DJ5Su.png)

Happens on my chromebook. I have yet to test any other machines.

**Comment by Tricky1975** [comment]
I tried this on my Mac using Opera and there the "X" for clearing a rating appears just after the bots I can use to rate which I believe is the correct place.

**Comment by acidpoison** [comment]
Phantasar, your screen resolution is pretty big, so you won't encounter the problem. If you want to see the bug for yourself, zoom in so that the overview and rating bar separates to avoid overlapping.

Just tested it on my Windows 7 computer with chrome and it happens again. I had to zoom in 150% to see it though.
![bug ss](http://i.imgbox.com/HpcoPkLW.png)

**Comment by hworld** [comment]
Fixed.
