### ISSUE TITLE
GameJolt Client isn't oppening

### ISSUE THREAD

**Issue by Fancy2209** [gamejolt/next-issue-tracker#1388]
**How are you using Game Jolt?**
Im using GameJolt to play games

**Please describe the issue you are having**
On GameJolt Client instead of opening up normally it oppens an app called nw.js
This isn't the first time it happends, last time I needed to unistall GameJolt Client and than Re install it.
![image](https://user-images.githubusercontent.com/64917206/81202245-d7c3b000-8fb5-11ea-9d18-6a8767763133.png)

**Comment by Fancy2209** [comment]
Last time I needed to re download it

**Comment by moeenio** [comment]
Does it happen after an update? On which operating system?

**Comment by Fancy2209** [comment]
Before Client was saying it was having trouble updating, Windows 7 is the OS im running on

**Comment by Fancy2209** [comment]
I needed to go into the Client files and open the client to update it

**Comment by Fancy2209** [comment]
But now it's working
