### ISSUE TITLE
Game Jolt Won't Reinstall

### ISSUE THREAD

**Issue by Daliek10** [gamejolt/next-issue-tracker#1391]
**How are you using Game Jolt?**
Since I have Windows I use that downloader.

**Please describe the issue you are having**
Game Jolt recently had an update so I had to reinstall it for the update, it was working perfectly fine but then when I got the setup it said something along the lines of "Setup has detected that Game Jolt Client is currently running. Please close all instances of it now" even though I had the Client closed. I went as far as deleting the Client and the problem persisted if this has been answered before sorry for asking.

(Btw if there's another comment exactly like this one it's because I accidentally posted it twice)

**Comment by WHYGAMEJOLTWHY** [comment]
try closing game jolt things other than installer/uninstaller in task manager

**Comment by Daliek10** [comment]
> try closing game jolt things other than installer/uninstaller in task manager

Ah, now it decided to work. Thanks tho.
