### ISSUE TITLE
PayPal button does nothing on "Buy Game" modal

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/next-issue-tracker#1392]
Clicking PayPal on the Buy Game modal does nothing when trying for a second time.
Windows 10 | Firefox and Client

Steps to reproduce:
1. Go to any paid game.
2. Click "Buy Game".
3. Click Paypal (this might work as per normal).
4. Fill in location info and proceed.
5. Cancel the transaction by just leaving/closing the PayPal transaction page.
6. Head back to any paid game and click "Buy Game" again.
7.  Click PayPal. Clicking should now do nothing.

**Comment by YLivay** [comment]
Confirmed and we have a fix in the pipeline.

**Comment by hworld** [comment]
The fix was pushed earlier this week.
