### ISSUE TITLE
Pages 249 and onward only show Page Not Found.

### ISSUE THREAD

**Issue by ectoBiologist15** [gamejolt/next-issue-tracker#1393]
**How are you using Game Jolt?**
Looking for games.

**Please describe the issue you are having**
In search or when viewing a tag from the main page, I first noticed going to the last page just gave me Page Not Found. I tracked it down to page 248 being the last page that worked.
I first reported this over email on 17/11/19 (dd/mm/yy) and got the response that "We hope to have this resolved in the near future."
It has been over six months and it still hasn't been fixed?

**Comment by Tricky1975** [comment]
Dupe #1234

**Comment by ectoBiologist15** [comment]
no reason to leave a dupe open
