### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by JUNALULOCO** [gamejolt/next-issue-tracker#1394]
**How are you using Game Jolt?**
Client, in a x86 pc

**Please describe the issue you are having**
In some cases, when i open a porfile like the Ultimiun one, it apear on the left side, i cant se nothing, jus the option "Report user" and it hapened to me 3 times until today in this week

**Comment by Tricky1975** [comment]
Perhaps you need to be more descriptive in the subject line than just "Help!"  
On a forum such a subject is already frustrating and on an issue tracker it's even essential that the subject is more descriptive than that. 

Only seeing the menu to report a user when you ask for their profile is however indeed pretty odd to me.

**Comment by hapurubokka** [comment]
I believe this has been fixed in https://github.com/gamejolt/gamejolt/pull/519
