### ISSUE TITLE
f-cdn.gamejolt.net’s server IP address could not be found.

### ISSUE THREAD

**Issue by JacksonBarker** [gamejolt/next-issue-tracker#1407]
**How are you using Game Jolt?**
Trying to install Game Jolt Client from https://gamejolt.com/client

**Please describe the issue you are having**
When clicking "DOWNLOAD FOR WINDOWS" or clicking other platforms then clicking"DOWNLOAD WINDOWS",
I get redirected to https://f-cdn.gamejolt.net/data/games/5/162/362412/protected-files-cdn/5f1b467ae10b7/gamejoltclientsetup.exe?secure=(a random string of characters),
and Chrome gives me the error: f-cdn.gamejolt.net’s server IP address could not be found.

I am running the latest version of Chrome, Windows is up to date,
and if the f-cdn is a server location, then I am in Ontario, Canada

**Comment by foxxy0607** [comment]
you fix it yet?

**Comment by JacksonBarker** [comment]
I am no longer having this issue, I do not even remeber opening it.
