### ISSUE TITLE
Gamejolt Portfolio site isn't availiable

### ISSUE THREAD

**Issue by stevenharmongames** [gamejolt/next-issue-tracker#1412]
**How are you using Game Jolt?**
I'm a long time user of GameJolt (dev). I use it for hosting my games, secret work in progress prototypes, and my portfolio.

**Please describe the issue you are having**

I've had a custom static site with a Google domains domain as my Gamejolt portfolio for a few years now. It's been a blessing and worked fantastic, but today I checked and noticed the portfolio sites down (they just redirect to gamejolt) and the cap seems to be at 0 and "loading" instead of the usual 50. I can't upload a new version of the site or do anything for that matter.

![image](https://user-images.githubusercontent.com/35232072/91129992-c2a38780-e65f-11ea-9f59-2581eb7f6482.png)

**Comment by hworld** [comment]
Looking into this now! We did a big site migration and are still going through some issues regarding uploading.

**Comment by hworld** [comment]
Part of this should be fixed. You should now be able to access your domain. You may have to delete your browser cache if your browser ended up caching the redirect.

Still looking into why it failed to upload builds.

**Comment by hworld** [comment]
And uploads are fixed again now!
