### ISSUE TITLE
Input-Box of private chat disappears with long chat-history on IE11

### ISSUE THREAD

**Issue by MausGames** [gamejolt/next-issue-tracker#143]
![chat_bug](https://cloud.githubusercontent.com/assets/6109189/6446195/b10ace06-c109-11e4-822c-5f8cd56b4e48.png)

The panel on the left side has a long history and the input-box disappears while loading - the panel on the right looks normal. 

on **IE11**
**Opera beta 28.0** and **Firefox 36.0** look normal

**Comment by MausGames** [comment]
(Pfff, forgot he is tracking title-renamings - me and my perfectionism)

**Comment by hworld** [comment]
Darn, I thought I fixed that! Poop. I'll have to grab an IE11 VM to test.

**Comment by MausGames** [comment]
Seems to work when adding **height: 0;** to the class **chat-window-main**.
Looks still normal on Firefox then.

**Comment by hworld** [comment]
Yo @MausGames, is this fixed now for you? I added it, but can't test.

**Comment by MausGames** [comment]
Looks fine now on IE, and still fine on a couple of other browsers.

**Comment by MausGames** [comment]
Oh wait, after looking again on the normal multiuser-chat (where the input-box was also gone), the box seems to be also stretched to the side:

![flex](https://cloud.githubusercontent.com/assets/6109189/7549963/ba624e6a-f64d-11e4-82b2-5e4d1cbb3c90.png)

Would be fixed this time with setting **width: 0;** on **chat-window-output-wrap** and it still looks the same on Firefox and Opera. Seems IE implemented Flex a bit differently.

**Comment by hworld** [comment]
Bah. Is this fixed now? I pushed out the change.

**Comment by MausGames** [comment]
Looks magnificent.

**Comment by hworld** [comment]
Finally! haha
