### ISSUE TITLE
Can't play or unistall games

### ISSUE THREAD

**Issue by Lolm0** [gamejolt/next-issue-tracker#1433]
**How are you using Game Jolt?**
I am using it to play games.

**Please describe the issue you are having**
 one time I went into the files and clicked on an application.
And played some of the game but now I can't restart the game nor uninstall it.

**Comment by humanfoxy8866** [comment]
same i cant uninstall my game i click it and it doesn't work

**Comment by Lolm0** [comment]
I figured it out you delete all files related to gamejoit
