### ISSUE TITLE
Number of incoming chat not shown in page title.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#146]
Quote: OmnipotentPotato (copied to GitHub as requested) ;)
It's just a small thing, but it's really annoying how new chat messages are not shown in the page title.

Like for the chats over on the right (Dev Chat, Let's Players, etc...) if you open it, whenever there is a new message when you are off page it is added to the title of the page. 

For some reason this really helpful feature isn't on WTTF.

**Comment by hworld** [comment]
Done
