### ISSUE TITLE
YouTube videos are displayed inside a card instead of being embedded

### ISSUE THREAD

**Issue by forestrf** [gamejolt/next-issue-tracker#1475]
**How are you using Game Jolt?**
Posting updates of my game

**Please describe the issue you are having**
YouTube videos don't embed automatically anymore. Before they were big and easy to watch, now they are inside a small card that discourages interacting with, plus showing a link on the post that makes reading it more difficult as there's now extra text (the video link) that's in the way of the actual message, and so discouraging using a feature for videos other than uploading it directly to Gamejolt. This hurts helping to grow both gamejolt and youtube at the same time, locking the community to Gamejolt and segments the fan base.
An easy fix would be to embed youtube videos (and any other video) like it was done before.

**Comment by hworld** [comment]
We saw way less engagement/views with the YouTube embed system than we did with the Game Jolt video system. If you want to get people to watch your stuff on Game Jolt, posting the content directly to Game Jolt will give you the most actual views. 

When creators use Game Jolt as a secondary channel, they end up getting secondary results sadly. While it's easier to manage from a game dev/content creator to just upload to youtube and then link within Game Jolt, it ended up stunting the the actual engagements that were possible within Game Jolt.

The YouTube embeds also don't work nearly as well with the app that's coming out. Again, if you really want the views and actual audience, using Game Jolt as a primary content platform is going to serve the best.
