### ISSUE TITLE
Homepage is taking too long to compile.

### ISSUE THREAD

**Issue by hworld** [gamejolt/next-issue-tracker#157]
It's currently taking way too long to load/compile in, especially noticeable on mobile.

**Comment by MausGames** [comment]
Have you tried https://developers.google.com/closure/compiler/ (at least for the JS part)?

**Comment by hworld** [comment]
Sorry, this was more for me to remember. I know what I'll be doing to fix it. "compile" means that the DOM elements are taking too long to construct because it's making way more than it needs at the time.

**Comment by hworld** [comment]
Fixed.
