### ISSUE TITLE
Unneccessary scroll bar on browser games in large display

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/next-issue-tracker#166]
Displays larger than game window display empty scroll bar.
Tested on both HTML and Unity games. I'm assuming this will happen for all browser games.

![GJbugscrollbar](http://s21.postimg.org/ro6y9sxpj/NEXTbug.png)

**Comment by hworld** [comment]
It's to stop the jerk caused when the content area of the modal animates large than the height of the window. It's generally a better trade-off than possible jerky animations.
