### ISSUE TITLE
Clicking link to author of fireside post on home screen directs you to an empty page

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/next-issue-tracker#169]
If you go to the home page and click the link of the author of a fireside article, you are redirected to a nonexistent page instead of the author's fireside page.
![author bug](http://s10.postimg.org/x6dph7qqh/NEXTbug1.png)
![empty page](http://s16.postimg.org/75zrnqyj9/NEXTbug2.png)

**Comment by hworld** [comment]
Fixed.
