### ISSUE TITLE
Filters not filtering out games correctly

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/next-issue-tracker#172]
I selected the flash and html filter but I got windows games mixed in with flash and html games.
![bug ss](http://s21.postimg.org/4vyqn4rhj/Screenshot_2015_03_18_at_11_20_57_AM.png)
![bug ss 2](http://s14.postimg.org/v2hltvrxt/Screenshot_2015_03_18_at_11_18_56_AM.png)
Other filters may be not be filtering out games correctly. I haven't tried any others yet.
You might also want to check and see if the filters may be filtering out games that they are supposed to show.

**Comment by hworld** [comment]
It was a bug with the new indexer I pushed out a couple weeks ago. It wasn't correctly filtering out hidden and removed games.
