### ISSUE TITLE
Browser game needs to be clicked before it can be played.

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/next-issue-tracker#178]
When playing games in the browser, you need to click the game box or it won't sense your input.

This is not a problem after playing ads because it has a play button that forces you to click the game box to start loading the game.

A temporary way to fix this would be to add a play button in the game box, ad or no ad, to ensure that all input is picked up by the game. This is a little repetitive since you have to click 2 play buttons to start playing.

**Comment by hworld** [comment]
Would you be able to include a test game URL?

**Comment by acidpoison** [comment]
HTML
http://wttf.gamejolt.com/games/iron-snout/33540
Flash

Unity
http://wttf.gamejolt.com/games/chickenjump/45678

Basically it happens to every browser game that doesn't use a **Click to Start** button.

**Comment by hworld** [comment]
Couldn't really figure out a way around this, sadly. Looks like Scirra (construct 2) couldn't figure it out, either: https://www.scirra.com/forum/set-focus-on-iframe-when-game-loads_t69600
