### ISSUE TITLE
Notifications misdirect to homepage

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/next-issue-tracker#179]
I can't replicate it, but I'm going to put it here just in case this really is a bug.

If you click a notification that directs you to the page you are already on, it will direct you to the home page.

I replied to a comment on petnik, and then clicked a notification that said somebody commented on petnik, and it took me to the home page.

**Comment by hworld** [comment]
Oh, it's because notification linking isn't fully functional yet. Comments aren't linkable just yet. I've got it on my list of things to do to finish out notifications. heh

**Comment by hworld** [comment]
Got comment notifications working and linking correctly. The only thing left is forum notifications, but I'll track that in a separate issue.
