### ISSUE TITLE
Filtering playlist in a continued page doesn't show any games

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/next-issue-tracker#182]
If you are on any page in a playlist other than the first page, the filters won't work and will not show any games.

I was scrolling through my playlist called "Play Me" and was on the second page. I used a Browser Games filter and no results showed up, even though it said there are results.

![gj bug ss playlist](http://s9.postimg.org/knmz6cw4v/Untitled.png)

It happens in Followed Games too.
It happens with all filters.

**Comment by hworld** [comment]
Fixed.
