### ISSUE TITLE
Markdown support for footnote style links is broken in comment boxes

### ISSUE THREAD

**Issue by variousauthors** [gamejolt/next-issue-tracker#186]
When writing markdown I usually write my links like this:

```
Here is a [link][0].

[0]: http://www.example.com
```

Which would be rendered as (minus the quote),

> Here is a [link][0].

In the comment editor on the game page, that markdown doesn't produce correct results. I have captured an example:

![write](http://i.imgur.com/ZzIfeVr.png)
![preview](http://i.imgur.com/q2b69Rb.png)

Come to think of it, I'm not actually sure the footnote style is canonical markdown, or whether it is github flavoured. However, I love the footnote style and I hope my love moves you to fix this ^o^//

P.S. thank you _so_ _so_ _so_ much for supporting markdown in all text inputs. Markdown has become part of my internet ideolect and I often enter markdown in text boxes whether it is supported or not (like on facebook I sometimes find myself using _this_ for emphasis...). I'm really happy when I find markdown support where I wasn't expecting it.

P.P.S. I'm Ziggy (Arrogant Gamer)! Various Authors is my hacker alias.

[0]: http://www.example.com

**Comment by variousauthors** [comment]
p.p.p.s who is this guy writing love notes in post-scripts to github issues!? Get a life, amarite?

**Comment by hworld** [comment]
You know, as silly as this is... the library we use isn't 0-indexed. So if you change it to a 1 instead of a 0 it'll work. O_O

**Comment by hworld** [comment]
Oh, and yeah, markdown FTW! I'm trying to get absolutely everything into markdown. News articles, game descriptions, user profiles, forum posts. Mwuahaha!
