### ISSUE TITLE
'More Game News' shows the article you're on

### ISSUE THREAD

**Issue by NikSudan** [gamejolt/next-issue-tracker#189]
Seems a little bit pointless to show it again.

The section should hide when the only article is the article you're viewing.

![](http://i.imgur.com/VuqmhQa.png)

**Comment by hworld** [comment]
I KNOW THAT OKAY!?

**Comment by NikSudan** [comment]
THERE'S NO NEED FOR OUTSIDE VOICES!!

**Comment by hworld** [comment]
I'm sorry, nik. :cry:
