### ISSUE TITLE
Search bar bug

### ISSUE THREAD

**Issue by NickRock** [gamejolt/next-issue-tracker#194]
When searching something and then go back, it doesn't remove the text.
if that's a bug.
I noticed that in comments too but it got fixed. ha.

**Comment by hworld** [comment]
You're talking about the search box that's always visible in the top-right? If that's the case, then it's supposed to keep your latest search in there while the site is open.

**Comment by NickRock** [comment]
oooh now I get it, it seemed like a bug because we didn't have that feature in the old gamejolt
