### ISSUE TITLE
Extra spacing on the right of the homepage causing it to be horizontally scrollable on mobile.

### ISSUE THREAD

**Issue by NickRock** [gamejolt/next-issue-tracker#209]
There's a white gab if you scroll at the right

I'm using HTC desire 310, it runs Android 4.2.2, on chrome and the screen is 4.5 inches 

![screenshot_2015-04-06-17-19-04](https://cloud.githubusercontent.com/assets/11754980/7100615/0e75cbb4-e035-11e4-9471-827f92822ffe.png)
![screenshot_2015-04-06-17-19-08](https://cloud.githubusercontent.com/assets/11754980/7100617/1379b558-e035-11e4-8772-248efdc95b53.png)

**Comment by NikSudan** [comment]
I get the same on iPhone 6. I think it might be an issue with the sliders.
