### ISSUE TITLE
Empty spaces when suggesting games in home page

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/next-issue-tracker#210]
On the home page, there are only 4 games suggested for a category when there is room for 6.
![bug ss](http://s6.postimg.org/3mqvsyn0x/Screenshot_2015_04_11_at_6_43_24_PM.png)
![bug ss](http://s6.postimg.org/yi82k3uhd/Screenshot_2015_04_11_at_6_43_29_PM.png)
![bug ss](http://s6.postimg.org/66min2akx/Screenshot_2015_04_11_at_6_43_34_PM.png)

**Comment by NikSudan** [comment]
It's a responsive issue. If you hide the chat, you'll see that they flow nicely onto one line.

Possible fix would be a variable amount of games being shown depending on your resolution.

**Comment by hworld** [comment]
This is a race condition in the code where it's not getting the correct width of the inner container to decide how many thumbnails to show. I'm working on a fix.

**Comment by hworld** [comment]
Is this fixed? I pushed a pretty big update today for stuff like this.

**Comment by acidpoison** [comment]
I'll check it next time I'm on my chromebook.

**Comment by acidpoison** [comment]
Yup. It now shows 3 at a time instead of 6.
