### ISSUE TITLE
Private chat indicator doesn't show up/shows up wrong

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/next-issue-tracker#211]
When viewing a private chat, the indicator either doesn't show up, or shows up and gets stuck.

![next bug](http://s6.postimg.org/esudlebyp/Screenshot_2015_04_11_at_8_16_49_PM.png)
I am viewing Aftermath's chat, but the indicator is next to Bits and Bros.

**Comment by hworld** [comment]
Fixed.
