### ISSUE TITLE
Voltage bar is behind links

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/next-issue-tracker#212]
I can't rate games lower than 4 volts. The voltage bars need to be stacked underneath.
![bug](http://s6.postimg.org/98r328rv5/Screenshot_2015_04_11_at_10_35_52_PM.png)

**Comment by hworld** [comment]
Fixed yeah?

**Comment by acidpoison** [comment]
Yeah. It even changes format when I use the X shortcut.
