### ISSUE TITLE
Comments section links and buttons are unclickable

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/next-issue-tracker#213]
Not sure if this is temporary or not.

I can write comments into the box, but the comment buttons and the links to other pages of comments as well as what is markdown and preview link are unclickable. The usernames and reply buttons are unclickable too.

It could just be me. I am using chrome on a chromebook.

**Comment by NikSudan** [comment]
Links work for me, I'm on Chrome too. Does it work if you don't click on the comment box?

**Comment by acidpoison** [comment]
Works now. I'm not sure why it didn't work before.

**Comment by acidpoison** [comment]
It seems to only happen on my chromebook, but it works fine on PC. I'm not really sure what it is.

**Comment by acidpoison** [comment]
I can comment and click buttons on the news comments section, but not the game news section? It boggles my mind...

**Comment by hworld** [comment]
Hey, not sure what you mean. The news comments section vs the game news section?

**Comment by acidpoison** [comment]
It seems to be a Chromebook specific issue, nothing else I use seems to have this problem.

I can type text into the comment box, but anything clickable in the comments section of a game (comment button, markdown link, avatars, usernames, upvote buttons, reply buttons) don't work. However, comment sections for news articles seem to work fine.

**Comment by acidpoison** [comment]
Seems to be working now.
