### ISSUE TITLE
Remove game from playlist

### ISSUE THREAD

**Issue by NickRock** [gamejolt/next-issue-tracker#214]
When you remove a game from the playlist page it pops up a confirm message box but when you remove it from the game's page it doesn't

**Comment by hworld** [comment]
Do you think it should confirm in either spot?

**Comment by NickRock** [comment]
Yup, I think it would be better

**Comment by NikSudan** [comment]
Any removal feature should confirm.

**Comment by hworld** [comment]
Hmm, I've thought about it, and I actually don't want the confirmation here. It's very easy to go back in and re-add it to the playlist in case you accidentally click, but in the library it'll actually remove it from the view. I'm going to keep how we have it.
