### ISSUE TITLE
The blips in the featured spot stay highlighted when page is not visible.

### ISSUE THREAD

**Issue by hworld** [gamejolt/next-issue-tracker#218]

**Comment by acidpoison** [comment]
Can I ask why this happens? Just curious.

**Comment by hworld** [comment]
I explain in my comment on #232. It's basically angular's fault. They broke stuff in regards to animations and set classes. I believe their latest changes fix it, but it hasn't been released in a new version just yet. They should release a new RC this week.

**Comment by hworld** [comment]
I rolled back to a previous version of the animate library. I won't upgrade again until it's fixed.
