### ISSUE TITLE
Chat breaks when someone posts a long message

### ISSUE THREAD

**Issue by NickRock** [gamejolt/next-issue-tracker#233]
![capture](https://cloud.githubusercontent.com/assets/11754980/7549891/53c11b86-f653-11e4-94ed-28ac389f7886.PNG)

**Comment by hworld** [comment]
Which browser? I have the styling in place so that it breaks the word. There's not much more I can do if the browser isn't listening to me.

**Comment by NickRock** [comment]
I was using Firefox

**Comment by hworld** [comment]
Is it fixed now, then? I tried it on my machine with the latest Firefox and it wrapped correctly.

![screenshot from 2015-05-11 15 28 25](https://cloud.githubusercontent.com/assets/1024321/7574372/6a62e6c6-f7f2-11e4-92d5-db56dbccaf86.png)

**Comment by TrickyRachel** [comment]
I would love to try if this works properly in Opera, however I do not feel game to spam any chatrooms or my friends.

**Comment by NickRock** [comment]
Something that I forgot to mention is that when I refreshed the page it got fixed so I think the bug was because of the bad internet connection I had that day, GameJolt should run in slow connections too

**Comment by hworld** [comment]
I did do some style changes to fix some other issues that may have been related. I am going to close this but feel free to open it again if it happens again.
