### ISSUE TITLE
Number of games of a developer bug

### ISSUE THREAD

**Issue by NickRock** [gamejolt/next-issue-tracker#234]
This guy has 3 games but in a game page it says that it has 7
![capture1](https://cloud.githubusercontent.com/assets/11754980/7550572/9f9e2316-f66f-11e4-9a4e-fef40182218b.PNG)
![capture2](https://cloud.githubusercontent.com/assets/11754980/7550573/a0335f9e-f66f-11e4-9995-6884c67eca3d.PNG)

**Comment by hworld** [comment]
Fixed.
