### ISSUE TITLE
Comment error on games

### ISSUE THREAD

**Issue by TrickyRachel** [gamejolt/next-issue-tracker#239]
![image](https://cloud.githubusercontent.com/assets/6297959/7576615/009e2216-f840-11e4-851b-e8cee7d159b9.png)

I could not see the comments for this game. Both pages (I mean page #1 and #2 appear broken.
They do show on the old site though. 
(This is the game I tried in the screenshot: http://wttf.gamejolt.com/games/nanovoid/55379)

P.S. I tried my own game "The Secrets of Dyrt". At first it said there there we no comments at all, but after a few seconds it says I got 49 comments and the system even shows them. I wonder what exactly happened as one game does show it well and the other doesn't... hmmm....

**Comment by TrickyRachel** [comment]
In a later test, both games now return an "Internal Server Error" (of the "dubious" sort, whatever that means).

**Comment by hworld** [comment]
There are intermittent issues on the server. It's not a code issue. The DB is under pretty heavy load. We're looking into it.
