### ISSUE TITLE
chat online user link

### ISSUE THREAD

**Issue by Agrosis** [gamejolt/next-issue-tracker#256]
i wanna be able to right click on a user's name in chat so i can open in new tab, right now it just opens up in current tab

**Comment by hworld** [comment]
In the friends list?

**Comment by Agrosis** [comment]
nah on chat in the active user list

**Comment by hworld** [comment]
I am able to right click on a user in a particular room in the users list and open in new window.

**Comment by Agrosis** [comment]
for some reason i cant right click on anything on the new gamejolt >_<

**Comment by Agrosis** [comment]
nvm had to restart browser for some reason, sorry bout dat
