### ISSUE TITLE
Activity feed link to reply on news article broken.

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/next-issue-tracker#264]
Clicking a link in the activity feed linking to a reply to a comment in a news article directs to page not found screen.

Happens in both latest activity and activity feed.

**Comment by hworld** [comment]
I tested this out a ton and it worked just fine. I'm thinking maybe the news article was removed, or maybe the comment was removed by a mod or something.

**Comment by acidpoison** [comment]
Still happens to me, tested on multiple different comments and news articles.

It's probably just me, I'll have to try my school computer.

**Comment by hworld** [comment]
Can you copy the link and paste it here?

**Comment by acidpoison** [comment]
http://wttf.gamejolt.com/games/spacefok/news/fps-too-slow-for-you/43149/#comment-678567

http://wttf.gamejolt.com/games/a-long-journey-an-episodic-anime-visual-novel-series/news/episode-2-re-released-today/60375/#comment-650631

http://wttf.gamejolt.com/games/jade/news/jade-future-platforms-everything/63257/#comment-635341

**Comment by hworld** [comment]
ah-ha. thanks!

**Comment by hworld** [comment]
Fixed! Nice catch!
