### ISSUE TITLE
Middle mouse button opens new tab

### ISSUE THREAD

**Issue by PianoHands** [gamejolt/next-issue-tracker#273]
It's irritating the living piss out of me.

**Comment by hworld** [comment]
Just to clarify, is it opening a new tab when you middle click on a link? Are you trying to use middle mouse to scroll?

**Comment by YLivay** [comment]
Yup, he is.

**Comment by PianoHands** [comment]
Just trying to scroll, and it happens to be over a game or something.

**Comment by YLivay** [comment]
Compatibility setting to disable middle mouse click? :stuck_out_tongue:

**Comment by hworld** [comment]
Gonna close this for now. If more people complain I'll look into it.
