### ISSUE TITLE
Hot Games Resolution Issue

### ISSUE THREAD

**Issue by PianoHands** [gamejolt/next-issue-tracker#274]
on the hot games tab, if I click status it hides the window behind the chat screen.

**Comment by hworld** [comment]
It hides the window behind the chat screen? Technically it should, I think. Chat is supposed to be in front of everything else.

**Comment by PianoHands** [comment]
I would argue that in this scenario, if you want chat open and you are filtering, you should be able to filter without closing chat.

**Comment by YLivay** [comment]
hit C to minimize chat, its super fast to pop in and out.
It's a choice of design, as the chat does obstruct some of the visible page it doesn't make sense to have them both focused at the same time.
