### ISSUE TITLE
My ideas!

### ISSUE THREAD

**Issue by Phanthomphax** [gamejolt/next-issue-tracker#278]
# All new developer mode
### So what is this?
This adds an developer mode button in your game page, in your **own game** where it allows you to manage the game, I do like the *Manage game* thingy, but it seems old for now.

### How could this work?
By pressing _Manage_ on the game page of your game, you can edit description by pressing it, like [Scratch](http://scratch.mit.edu), it allows you to edit description on one press. You can edit everything without waiting for the _loading_ thingy, which annoys at the moment like [Sims 4](http://thesims.com).

### What are the advantages?
* Easy way to modify game pages
* No need for hassle to go to Dashboard
* More interactive
* More HTML5 feel

##### _What do you mean?_
_If you're asking what I really mean, then here. In your own **game page**, there is a button that appears, called **Manage**, that replaces **Follow game** that allows you to follow your own game. Seriously, when you **Follow** your game, you get annoyed of your own news. Not to mention to remove the **Follow** feature, I mean, replace that when being in your own gamepage (This shows only for you, and for visitors of your game, Follow button replaces Manage). Pressing **this**, allows you to press descriptions then edit it without going to another page._

# Multi-Chat & Group & Other chat features
### What is this feature?
This adds Groups for beta testing (as mentioned in Gas), functions the same as mentioned, but NOT with that Gas thingy. Not just that, better chat. You can open chat and minimize other, while the Friends is hidden, and multi-chat. This group chat like I meant is like the group chat on Facebook/Skype. It's way easier to talk in a group than having to add a friend on Skype to talk to each other. The Multi-Chat saves space when the Friends is closed, no needing to reopen them. In the *Other chat features*, this one is where we could still interact inside gamejolt without having to close chat, and also, an ability to resize, send pictures, emoticons, report feature, and markdown (not all of markdown, such as lists, it will break the chat a little). Gotta save space.

### How could this work?
I have no idea how to make this *work* but, in the meantime, they could, like, work like Facebook? But in the Beta Testing one, as I said, it functions as *mentioned in Gas*. It seems like a Cool feature where you can send beta test. In the Multi-chat, like in facebook, but when the friends tab is opened, this is hidden and there's a tab-like symbol in their next of their chat, that allows you to chat in them, without having to re-open Friends tab. To close, press close while in chat or press the symbol. To do multichat again, just press "Minimize" then you can see the tab-like symbol, then you are free to hide the friends tab and minimize the chat.

### What are the advantages?
* **Multichat:**
* Easy to chat without opening Friends list
* Saves more space in browsing
* Helpful

* **Group:**
* Easy to make Beta testing groups, send files (as a owner), report issues (as a tester), and give out screenshots of new features without having to send them into a image hosting site.
* More ways to communicate with others without to use Skype to prevent much multitasking
* Better way to talk to each other without having to open friends tab to talk to each of them in one chat each.

* **Other chat features:**
* New ways to chat, without having to close the chat
* Emoticons that makes chat easier
* Resizing allows you to resize in many dimensional spaces, or you want it to fill up your screen if it's a chat. It also allows you to resize it small a bit to save space
* Sending pictures have never been easy without commenting.
* Markdown makes the chat fun with bold & stuff (not all the markdown)
* Report people who is abusive or doing somewhat bad.

## Thanks! - Phanthomphax

**Comment by Phanthomphax** [comment]
**_Please... I have worked hard to think about this, not that I mean, work hard. I mean, I've been thinking hard_**

**Comment by YLivay** [comment]
__The All new developer__ mode doesn't seem well thought of, there are a ton of non editable things that more often than not require more screenspace to manage. pooping it up in the same screen will just make things look cluttered.

__Multi-Chat & Group & Other chat features__ we have plenty of plans for chat, don't worry, tho I don't think we'll do markdown or pictures in chat _(shudder)_

**Comment by hworld** [comment]
@Phanthomphax, can you please put this in the suggestions forum on GJ? I want to keep the issue list for bugs or single features for now. Gonna close this.
