### ISSUE TITLE
Comment input box doesn't clear when you add a comment.

### ISSUE THREAD

**Issue by hworld** [gamejolt/next-issue-tracker#84]

**Comment by Tricky1975** [comment]
I found this bug on Fireside as well, long before I was granted access to the GameJolt Next testside. Caused by the same issue? (I have not yet commented any games via the new site as I didn't want to spam anybody).

**Comment by hworld** [comment]
Same issue, yeah. I haven't looked into it yet, but will soon.

**Comment by hworld** [comment]
Fixed on GJ Next.
